### ISSUE TITLE
问题：一个脚本多个网站签到 + 请求：渲染 `执行结果` 处的数据，比如可以有超链接、换行符等的

### ISSUE THREAD

**Issue by miiwu** [inu1255/soulsign-chrome#100]

**Comment by yi-Xu-0100** [comment]
好多个类似的网站？
这个插件应该是提倡分离的，不需要弄成聚合的，除非是同一域名下的。
当然如果你需要聚合， 域名那里多写几个应该也行

**Comment by Miao-Mico** [comment]
> 好多个类似的网站？
> 这个插件应该是提倡分离的，不需要弄成聚合的，除非是同一域名下的。
> 当然如果你需要聚合， 域名那里多写几个应该也行

欸，我想的是，能不能通过修改 @param 而不是 @domain，修一次脚本，之后只需要配置就好了，每次都编辑源脚本挺麻烦的。
还有，看了看，似乎 @loginURL 没提到可以多个，我想增加不同的 @domain 参数可能有点问题。 
综上，我想用 @param 似乎也不太行啊，登录 url，只有一个。

还望赐教。

**Comment by yi-Xu-0100** [comment]
在我的使用过程中，` @Domain` 参数主要限制了脚本中的跨域请求，在脚本作者的京东签到脚本中，有使用多个域名的例子。 `@loginurl` 这个参数，我看到的是会设置为脚本管理页面的脚本名称的跳转链接，你可以试试，如果你不管这个，也没事。

我想你的意思是实现脚本模板的概念，域名设成参数的想法，但是现在对这块应该没有。我创作的多数脚本，大体内容都是相似的论坛，我做的3-4个都是修改原来的脚本，创建新的脚本。而且不同网站可能相似，但也有一些变化，这就造成基本还是需要多次测试通过，模板功能还是很差的，仅供参考。

**Comment by Miao-Mico** [comment]
> 在我的使用过程中，` @Domain` 参数主要限制了脚本中的跨域请求，在脚本作者的京东签到脚本中，有使用多个域名的例子。 `@loginurl` 这个参数，我看到的是会设置为脚本管理页面的脚本名称的跳转链接，你可以试试，如果你不管这个，也没事。
> 
> 我想你的意思是实现脚本模板的概念，域名设成参数的想法，但是现在对这块应该没有。我创作的多数脚本，大体内容都是相似的论坛，我做的 3-4 个都是修改原来的脚本，创建新的脚本。而且不同网站可能相似，但也有一些变化，这就造成基本还是需要多次测试通过，模板功能还是很差的，仅供参考。

对，我想的是你说的这个意思。
我现在自己用的时候确实也是一个网站复制一个脚本。

对于 js 脚本和网络相关的，其中的概念，好多我本身是不了解的，只是可以在表面上改改。
琢磨琢磨先。

**Comment by yi-Xu-0100** [comment]
从我近期的制作脚本过程来看，是有一部分网站使用的是一个模板，可以作为直接修改域名完成。

但是只要网站有一定的自定义属性，就容易造成类似网站不同脚本，所以最好还是复制粘贴，重新测试。

**Comment by Miao-Mico** [comment]
我在想，能不能写一个 @domain ，可以访问所有指定的网站。
这个是不是跨域管理范畴的呀。

**Comment by yi-Xu-0100** [comment]
> 我在想，能不能写一个 @Domain ，可以访问所有指定的网站。
> 这个是不是跨域管理范畴的呀。

`@Domain` 可以指定多个域名， 然后在一个脚本中就可以访问不同域名的链接。
但是从网站特异性和安全性的角度来说，不推荐。

如果你想在参数中设置域名，`@Domain` 指定为任意，以满足使用脚本时才去设置参数的效果，安全性来说感觉不好（个人觉得，不太了解这方面，但是浏览器是希望你知道你跨域访问了的，而不是交给一个黑盒，让他可以访问任意）。

模板的话，我参考过 marvolo666 写的一个[模板](https://github.com/inu1255/soulsign-chrome/blob/master/public/demos/ShadowSocksR.js)，但这个没有作为脚本发布，而是放在脚本的公共脚本作为参考。

**Comment by Miao-Mico** [comment]
哈哈，但是如果反过来想，如果 `@domain` 指定成什么都不许访问，或者干脆把 `@domain` 去掉，通过参数列表静态/动态配置访问的域就好啦。
~~对，就像油猴那样吧，我这是胡说的，因为我不知道 `@domain` 在这里面是起什么作用的，也可能得改扩展。~~


哇，原来我一直在 戳 Domain 这个朋友，在这里说声对不起了。
O, I have been mentioning Domain, sorry, friend.

**Comment by yi-Xu-0100** [comment]
我想`通过参数列表静态/动态配置访问的域功能`是可以实现的。

但对于这个插件来看，感觉这给脚本的权力太大。

`@domain` 应该是作为过程量的检查，如果你把域名作为参数，`@domain` 必然需要作为参数可设置，而参数在脚本内可以设置或修改，也就是 `@domain` 可被重新设置或修改。这类似给了一个脚本全域名的管理权限。（个人推断，不知道有没有更好的方案避免）

效果类似需要一个 `@domain` 可设全局的方案。从签到插件看，脚本应该是对某一网站的签到，而不应该具有全域名的跨域访问， `cookies` 的使用都需要告知权限需要，域名访问可能也需要考虑安全性。

**个人观点不代表插件作者观点**。个人觉得全域名访问权限太大，现在的方案能让我不了解脚本内容的情况下，知道脚本使用了哪些东西。

**Comment by Miao-Mico** [comment]
> @domain 应该是作为过程量的检查，如果你把域名作为参数，@domain 必然需要作为参数可设置，而参数在脚本内可以设置或修改，也就是 @domain 可被重新设置或修改。这类似给了一个脚本全域名的管理权限。

这个的话，我觉得，在脚本运行之前就加载了参数列表，那不也不是脚本管理域名，而是人在管理。这样也是只能访问固定的域名列表，我觉得跟脚本头写域名没啥区别。
如果担心脚本私自提权，把参数封装起来，只给脚本提供读取，不提供修改，本身传入脚本的参数也不该可以被修改。

**Comment by yi-Xu-0100** [comment]
``` js
	let request = axios.create({ timeout: 10e3 });
	request.interceptors.request.use(function(config) {
		let m = /https?:\/\/([^:\/]+)/.exec(config.url);
		if (!m) return Promise.reject(`domain配置不正确`);
		let ss = m[1].split('.');
		if (!task.domains.reduce(function(a, b) {
				if (a) return true;
				let dd = b.split('.');
				if (dd.length != ss.length) return false;
				for (let i = 0; i < ss.length; i++) {
					if (dd[i] != '*' && ss[i] != dd[i])
						return false;
				}
				return true;
			}, false)) return Promise.reject(`domain配置不正确`);
```

从插件源码中，我看到检测方式应该是，当调用 `axios` 函数时，会用正则匹配其中的访问 `url` , 如果域名使用参数传入，则过程中无法用这种方式检查。我不太确定有没有其他方式检查过程。如果没有，而使域名作为参数传入，过程必须舍弃检查，那脚本其实内部是可以自由使用该函数的，即不一定要用参数传入的域名去自行字符串拼接出访问的 `url` ，而脚本使用者并不知道这一点。

现在这种方式，所有的访问会被 `@domain` 参数检查，对脚本使用者来说，是可以不用管脚本内部的细节，也可以知道脚本需要的访问哪些域名，个人认为较为安全。

**Comment by Miao-Mico** [comment]
> ```js
> 	let request = axios.create({ timeout: 10e3 });
> 	request.interceptors.request.use(function(config) {
> 		let m = /https?:\/\/([^:\/]+)/.exec(config.url);
> 		if (!m) return Promise.reject(`domain配置不正确`);
> 		let ss = m[1].split('.');
> 		if (!task.domains.reduce(function(a, b) {
> 				if (a) return true;
> 				let dd = b.split('.');
> 				if (dd.length != ss.length) return false;
> 				for (let i = 0; i < ss.length; i++) {
> 					if (dd[i] != '*' && ss[i] != dd[i])
> 						return false;
> 				}
> 				return true;
> 			}, false)) return Promise.reject(`domain配置不正确`);
> ```
> 
> 从插件源码中，我看到检测方式应该是，当调用 `axios` 函数时，会用正则匹配其中的访问 `url` , 如果域名使用参数传入，则过程中无法用这种方式检查。我不太确定有没有其他方式检查过程。如果没有，而使域名作为参数传入，过程必须舍弃检查，那脚本其实内部是可以自由使用该函数的，即不一定要用参数传入的域名去自行字符串拼接出访问的 `url` ，而脚本使用者并不知道这一点。

你说的这里不能检测 `@param / @params` 的意思吗? 可以啊 task.param / params，你要是担心如果没写参数是不是就没域名检测了，那可以把 domain 移动到 `@param` 里呀，像写原来的域一样，只不过把 `@domain` 替换成 `@param domain`。


```js
// ==UserScript==
// @name              v2ex签到
// @namespace         https://github.com/inu1255/soulsign-chrome
// @version           1.0.0
// @author            inu1255
// @loginURL          https://www.v2ex.com/signin
// @expire            900e3
// @param             domain 域名,www.v2ex.com
// ==/UserScript==
```


> 现在这种方式，所有的访问会被 `@domain` 参数检查，对脚本使用者来说，是可以不用管脚本内部的细节，也可以知道脚本需要的访问哪些域名，个人认为较为安全。

那默认不设置参数，就不允许访问任何域，只有自己设置才行，自己设置的自己肯定知道呀，或许安装->使用，中间多了一步，设置参数吧。
对于多了设置参数这一步，可以在 `@param` 那里，增加指定默认参数的方式，如果不填，就使用默认域，当然这个默认域可以遵循现在 `@domain` 的规则，这不就像 `@domain` 一样了啊。

说这些都是建议，希望作者看到咱们的讨论，可以考虑考虑，咱也不会修改，不然我就冲了，哈哈哈。

**Comment by yi-Xu-0100** [comment]
> 从插件源码中，我看到当前检测方式应该是，当调用 axios 函数时，会用正则匹配其中的访问 url

如果域名放在参数中，**脚本运行中**无法设置检查，因为你的 url 是用字符串拼接，当前插件的正则匹配方式是获取不到整个域名。

如果只是事先检查参数，脚本内部没有检查，这**要求脚本作者自觉**在内部不访问参数以外的域名，不透明，需要用户自己甄别。对用户来说，脚本内容一般不看，没法确定有没有未经声明的访问，**仍然需要用户查看脚本内容确定安全性(不确定用户是否有这方面的经验和考虑)**。

个人认为：**不能为了方便而不是必要，去造成可能的漏洞**。这不需要脚本作者设置域名，更方便，但是有漏洞（无检查，靠自觉，如果有翻版，内插恶意代码，有可能做成恶劣后果），容易造成这是**用户失察**的甩锅看法。

**Comment by yi-Xu-0100** [comment]
>那默认不设置参数，就不允许访问任何域，只有自己设置才行，自己设置的自己肯定知道呀，或许安装->使用，中间多了一步，设置参数吧。

个人没做过这方面的开发，不知道其他的"**在运行时，限制或者检查访问其他域名的方案**"，如果有，我想也就没有我所说的漏洞了。

**Comment by Miao-Mico** [comment]
> 如果域名放在参数中，**脚本运行中**无法设置检查，因为你的 url 是用字符串拼接，当前插件的正则匹配方式是获取不到参数中导入的域名。

这个我不清楚。
如果是的话，我的办法似乎就行不通了。

<details>
<summary>如果不是的话，展开查看</summary>

我说的当然不只是现在扩展能不能做到，我是希望可以提供一种思路。
当然了，能不能做到我不知道，不会这个。还是那句话，如果修改了还做不到，也只是到此为止了。

</details>

**Comment by yi-Xu-0100** [comment]
@Miao-Mico 我应该是弄错了他的检测方式，不怎么懂这块的传参。

作者的 `@domain`是支持模糊匹配的，所以你可以设置 `@domain` 参数为 `*.*.*` 和 `*.*` 去匹配大多数的域名（除非有更多级的域名需要访问）。

这样域名理论上都可以匹配了，也就是全局匹配，这样的效果可能没法看出脚本具体的域名访问了。你可以试试，应该能达到你想要的效果……

**Comment by yi-Xu-0100** [comment]
登录的 `@loginurl` 的话 应该没法匹配多个。你可以设置为介绍页面或者其他。

**Comment by yi-Xu-0100** [comment]
话说，为啥不弄个单页面，填上一些参数：域名，登录链接：等等。

下面可以直接生成相应的脚本内容。

这样单页面做成一个 html 放 github page 上，应该会挺方便。

甚至可以将模板设置为可选，以后有啥模板，用啥参数，直接从你这导出，思路仅供参考。

**Comment by Miao-Mico** [comment]
> @Miao-Mico 我应该是弄错了他的检测方式，不怎么懂这块的传参。
> 
> 作者的 `@domain` 是支持模糊匹配的，所以你可以设置 `@domain` 参数为 `*.*.*` 和 `*.*` 去匹配大多数的域名（除非有更多级的域名需要访问）。
> 
> 这样域名理论上都可以匹配了，也就是全局匹配，这样的效果可能没法看出脚本具体的域名访问了。你可以试试，应该能达到你想要的效果……

我怎么没想到啊，还有用 '*' 貌似可以匹配所有。

> 登录的 `@loginurl` 的话应该没法匹配多个。你可以设置为介绍页面或者其他。

这个我觉得不错欸，就是还没想好怎么搞。

> 话说，为啥不弄个单页面，填上一些参数：域名，登录链接：等等。
> 
> 下面可以直接生成相应的脚本内容。
> 
> 这样单页面做成一个 html 放 github page 上，应该会挺方便。
> 
> 甚至可以将模板设置为可选，以后有啥模板，用啥参数，直接从你这导出，思路仅供参考。

这个，是很好，但是我没学过 html 啊，其实 js 也是。
你这个想法我觉得可行，不过我发现可以 'require' 别的 'js' 脚本，那我就想着写一个模板脚本，专门用来被调用。

我还有个问题呀，这个是干嘛用的？
![image](https://user-images.githubusercontent.com/42897857/87843704-48a61300-c8e9-11ea-8b0a-357a15542aab.png)

**Comment by yi-Xu-0100** [comment]
>我还有个问题呀，这个是干嘛用的？

我不太确定，没用过，但是感觉是为某些网站的签到，会跨域请求一些东西吧……母鸡，我也小白，百度搜语法做的……

**Comment by Miao-Mico** [comment]
> 我不太确定，没用过，但是感觉是为某些网站的签到，会跨域请求一些东西吧…… 母鸡，我也小白，百度搜语法做的……

emmmm... 同🤣

**Comment by Miao-Mico** [comment]
> @Miao-Mico 我应该是弄错了他的检测方式，不怎么懂这块的传参。
> 
> 作者的 `@domain` 是支持模糊匹配的，所以你可以设置 `@domain` 参数为 `*.*.*` 和 `*.*` 去匹配大多数的域名（除非有更多级的域名需要访问）。
> 
> 这样域名理论上都可以匹配了，也就是全局匹配，这样的效果可能没法看出脚本具体的域名访问了。你可以试试，应该能达到你想要的效果……

这个 `*` ，好像只能一个脚本用啊，不知道为啥就那一个脚本可以，其他的就提示 `domain配置不正确`。
你可以去脚本列表看看我写的 sspanel 和 natfrp，natfrp 就不行。

**Comment by yi-Xu-0100** [comment]
? 我不太懂你的意思

他可能是根据 `.` 去切分域名的，所以，多级域名需要多级匹配吧。

**Comment by Miao-Mico** [comment]
> ? 我不太懂你的意思

唯独只有一个脚本可以使用 `*` 而不报错。

> 他可能是根据 `.` 去切分域名的，所以，多级域名需要多级匹配吧。

嗯嗯，可能如此，正则表达式也不太熟悉，我看不出来。

**Comment by Miao-Mico** [comment]
#103

**Comment by Miao-Mico** [comment]
#103
