### ISSUE TITLE
WPS打卡领会员似乎失效了？

### ISSUE THREAD

**Issue by NaCl-131** [inu1255/soulsign-chrome#101]
登录后还是显示不在线
![image](https://user-images.githubusercontent.com/60124911/87866899-b4f04780-c9b9-11ea-9128-5ecba026bdd8.png)

**Comment by yi-Xu-0100** [comment]
嗯……好像现在签到规则改了，需要获取一个微信端的 code 啥的，所以可能很难修复这个问题。
