### ISSUE TITLE
腾讯乐享自动签到

### ISSUE THREAD

**Issue by yosheng** [inu1255/soulsign-chrome#102]
运行 run 方法请求 check-in 接口返回 Not allowed in CORS policy.  信息 状态403
请求协助 翻了下其他脚本 貌似都没用到 跨域管理功能 请问该问题是我自己脚本错误
还是哪里遗漏了 请求指点

```javascript
// ==UserScript==
// @name              腾讯乐享签到
// @namespace         https://github.com/inu1255/soulsign-chrome
// @version           1.0.0
// @author            yosheng
// @loginURL          https://lexiangla.com/login
// @expire            900e3
// @domain            lexiangla.com
// ==/UserScript==
exports.run = async function() {
	var { data } = await axios.post('https://lexiangla.com/api/v1/points/check-in');
	return data;
};

exports.check = async function() {
    var { status  } = await axios.get('https://lexiangla.com/');
	return status == 200;
};
```

**Comment by yi-Xu-0100** [comment]
应该是请求中的 `headers` 中要添加相应的 `referer` 和 `orign`，你可以试试

**Comment by yosheng** [comment]
> 应该是请求中的 `headers` 中要添加相应的 `referer` 和 `orign`，你可以试试

```javascript
	var { data } = await axios.post('https://lexiangla.com/api/v1/points/check-in',null, {
		headers: {
			'isAjax': true,
			'x-requested-with': 'XMLHttpRequest',
			'sec-fetch-dest': 'empty',
			'sec-fetch-mode': 'cors',
			'sec-fetch-site': 'same-origin',
			'x-xsrf-token': '7jCEbswABYjDBf3enHw2Yth8vhccJ4OGMYjxXoq%2Fk1CBfj4GXqVKrbnt3t45qsiDHolbvaAbSqj83JnOrDqln0HjpRDRBYU6j2uCqs3S4IA%3D',
			'origin': 'https://lexiangla.com',
			'referer': 'https://lexiangla.com/'
		}
	});
```
还是跨域请求 😫

**Comment by yi-Xu-0100** [comment]
``` js
    var { data } = await axios.get('https://lexiangla.com/api/v1/points/check-in',
        {
            headers: {
                'Referer': 'https://lexiangla.com/',
                'Origin': 'https://lexiangla.com'
            }
        });
```

你的检查在线有点问题，我都没登陆，还是 `true`。我没有企业微信，没法测试，但是 `run` 测试的结果变了，不是跨域请求了，是 404 了，你查下问题吧……

**Comment by yosheng** [comment]
谢谢协助 跨域的问题透过 添加 header 中 referer 及 orgin 可以解决了 但检测是否登入 我还找不到办法 以及未登入进行签到 还是会默认成功 以下是我的脚本

```javascript
exports.run = async function() {
	var { data } = await axios.post('https://lexiangla.com/api/v1/points/check-in',null, {
		headers: {
			'Referer': 'https://lexiangla.com/',
            'Origin': 'https://lexiangla.com'
		}
	});
	if(data.code == 0) 
		return "签到成功";
	else{
		return data.msg
	}
	throw data || "签到失败";
};

exports.check = async function() {
    var res = await axios.get('https://lexiangla.com/staff');
	throw res
};

```
主要是验证的部份 不管我输入哪个登入后的url才能访问 都会自动转跳到 https://lexiangla.com/login 然后这又会转跳到 https://open.work.weixin.qq.com/wwopen/sso/3rd_qrConnect 这个3rd_qrConnect会在后面携带 QueryParamater

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/88162918-86d26800-cc44-11ea-894e-11ca89139a2a.png)


编辑里面有测试，然后 f12 看输出和网络请求和返回啥的

**Comment by yi-Xu-0100** [comment]
你检查是否在线，如果跳转的话，是登录页面，应该会有企业微信登录字样就是失败，没有就是登录成功了呗~试试这个逻辑检查行不行

**Comment by yosheng** [comment]
![screenshot](https://user-images.githubusercontent.com/15070744/88168457-08c68f00-cc4d-11ea-9b49-b2e5ace929e2.png)
使用 Cent Browser 版本 4.2.10.171（正式版本） （32 位） (Chromium 80.0.3987.163) 
没看到你说的那几个按钮😵 我目前是直接再 console面板里面 把代码贴进去执行😂 感谢帮忙 我再继续试试看

**Comment by yi-Xu-0100** [comment]
感觉你的是旧版本的插件，从仓库里下载压缩包使用

**Comment by yosheng** [comment]
谢谢回复 我从仓库里面获取最新版本 但反而无法添加脚本
![test](https://user-images.githubusercontent.com/15070744/88177755-f56ef000-cc5b-11ea-95f5-50b2613588cb.png)

**Comment by yi-Xu-0100** [comment]
是否可以将脚本分享出来？

**Comment by yosheng** [comment]
目前脚本如下
```javascript
// ==UserScript==
// @name              腾讯乐享自动签到
// @namespace         https://github.com/inu1255/soulsign-chrome
// @version           1.0.0
// @author            yosheng
// @loginURL          https://lexiangla.com/login
// @expire            900e3
// @domain            lexiangla.com
// ==/UserScript==
exports.run = async function() {
	var { data } = await axios.post('https://lexiangla.com/api/v1/points/check-in',null, {
		headers: {
			'Referer': 'https://lexiangla.com/',
            'Origin': 'https://lexiangla.com'
		}
	});
	if(/3rd_qrConnect/.test(data)) throw "请登入"
	if(data.code == 0) 
		return "签到成功";
	else {
		return data.msg
	}
};

exports.check = async function() {
    var res = await axios.get('https://lexiangla.com/staff');
    var array_of_matches = res.data.match(/(https:\/\/open.work.weixin.qq.com\/wwopen\/sso\/3rd_qrConnect)/g)
	return (typeof(array_of_matches) == "object" && array_of_matches == null)
};
```

我感觉不是这问题 新版本导出也会弹这个错 不知道是不是本身插件问题😰

**Comment by yi-Xu-0100** [comment]
我的添加成功了

![image](https://user-images.githubusercontent.com/25523606/88178530-1c79f180-cc5d-11ea-8b4a-616678e8fd5f.png)

**Comment by yosheng** [comment]
从脚本推荐是可以正常安装的 但如果手动点击添加或导出都会报错
![error](https://user-images.githubusercontent.com/15070744/88179149-091b5600-cc5e-11ea-8253-d991eea3752b.png)

**Comment by yi-Xu-0100** [comment]
我怀疑你本来脚本是在旧版本中的，新版本和旧版本有冲突，建议直接以你写的这个脚本在新版本中添加为好。注意，界面中，删除同名脚本，不然添加的话，是相当于修改的方式，可能还是不成功。

> ```js
> // ==UserScript==
> // @name              腾讯乐享自动签到
> // @namespace         https://github.com/inu1255/soulsign-chrome
> // @version           1.0.0
> // @author            yosheng
> // @loginURL          https://lexiangla.com/login
> // @expire            900e3
> // @domain            lexiangla.com
> // ==/UserScript==
> exports.run = async function() {
> 	var { data } = await axios.post('https://lexiangla.com/api/v1/points/check-in',null, {
> 		headers: {
> 			'Referer': 'https://lexiangla.com/',
>             'Origin': 'https://lexiangla.com'
> 		}
> 	});
> 	if(/3rd_qrConnect/.test(data)) throw "请登入"
> 	if(data.code == 0) 
> 		return "签到成功";
> 	else {
> 		return data.msg
> 	}
> };
> ```

**Comment by yosheng** [comment]
我把脚本的版本变更下就可以用了  现在是不能再插件管理的页面 点击 添加脚本 会报错
我换原生的 chrome 浏览器也不行

**Comment by yi-Xu-0100** [comment]
脚本推荐市场的版本号，每次修改的时候都需要提升，本地我不太知道这个会不会冲突，可能有影响。

然后，点击 添加脚本 会报错，我以前应该是有过，见 #92 ，修复在 #93 ，但是已经修复了，你确定使用的是最新版？

**Comment by yi-Xu-0100** [comment]
我实验了该仓库下的最新版，确实还是存在问题，需要作者 @inu1255  打包一下新版，修复这个问题。

你可以先使用我仓库下的[最新版本](https://github.com/yi-Xu-0100/soulsign-scripts/blob/master/build.zip)，这个版本是我个人打包的。

**Comment by yosheng** [comment]
> 我实验了该仓库下的最新版，确实还是存在问题，需要作者 @inu1255 打包一下新版，修复这个问题。
> 
> 你可以先使用我仓库下的[最新版本](https://github.com/yi-Xu-0100/soulsign-scripts/blob/master/build.zip)，这个版本是我个人打包的。

这个打包的正常 仓库的最新版本有问题😂 感谢帮忙！！
