### ISSUE TITLE
为什么 F12 之后看到 console 那里有发出来日志，但是网页上不更新？

### ISSUE THREAD

**Issue by Miao-Mico** [inu1255/soulsign-chrome#103]
为什么 `F12` 之后看到 `console` 那里有发出来日志，但是网页上不更新？
甚至 `最近执行时间` 会从刚开始的 `现在` 跳到 `xxx前`，`执行结果` 也不会变化。
是因为用到了 `async / await`，用得不对吗？

**Comment by yi-Xu-0100** [comment]
你的日志是指什么，网页上是指哪个网页？是指判断条件认为成功了，但是网页还是没有签到成功吗？
判断条件是否存在误判？执行结果指的是原网页签到是否成功吗？还是指插件页给出成功的信息（个人使用条件判断然后输出的）
只要执行了，不管成功与否，执行时间都会变更，除非一直卡在执行过程中。

**Comment by Miao-Mico** [comment]
> 你的日志是指什么，网页上是指哪个网页？是指判断条件认为成功了，但是网页还是没有签到成功吗？
就是某些变量的值。对的，通过日志成功后，网页顶部也有弹出执行成功的框，但是脚本 `执行结果` 那里没更新，`最近执行时间` 也不是现在，而是 `xxx前`。

> 判断条件是否存在误判？执行结果指的是原网页签到是否成功吗？还是指插件页给出成功的信息（个人使用条件判断然后输出的）
> 只要执行了，不管成功与否，执行时间都会变更，除非一直卡在执行过程中。
插件页给出的信息，判断应该没错，输出里看着没错，所以不知道咋回事，来问问是不是有其他我不知道的可能。

**Comment by inu1255** [comment]
@Miao-Mico 如果你是在脚本编辑界面点击`调试run`，是不会更新执行时间和执行结果的

**Comment by Miao-Mico** [comment]
> @Miao-Mico 如果你是在脚本编辑界面点击`调试run`，是不会更新执行时间和执行结果的

编辑界面是那里呀？
我点的是那个 `配置参数` 后面的 `立即执行`。
顺带一提，这个情况是一段时间一直这个样子，过一段时间又好了。

**Comment by Miao-Mico** [comment]
> @Miao-Mico 如果你是在脚本编辑界面点击`调试run`，是不会更新执行时间和执行结果的

如果是说 `IDE` 里面 `调试器` 的 `调试` 的话，我没有用过 `IDE` 的调试器，只是在 `VSC` 编辑之后，本地复制上去 `添加脚本`，直接 `F12` 然后点 `立即执行` 那个三角形，看 `Chrome DevTools` 里的 `Console` 栏的输出，其他的我也基本没动过。

我没从事过 `JavaScript` 的开发，不清楚你说的是哪里，也还没找到。
如果可以的话，请赐教。

**Comment by yi-Xu-0100** [comment]
> > @Miao-Mico 如果你是在脚本编辑界面点击`调试run`，是不会更新执行时间和执行结果的
> 
> 如果是说 `IDE` 里面 `调试器` 的 `调试` 的话，我没有用过 `IDE` 的调试器，只是在 `VSC` 编辑之后，本地复制上去 `添加脚本`，直接 `F12` 然后点 `立即执行` 那个三角形，看 `Chrome DevTools` 里的 `Console` 栏的输出，其他的我也基本没动过。
> 
> 我没从事过 `JavaScript` 的开发，不清楚你说的是哪里，也还没找到。
> 如果可以的话，请赐教。

新版本有调试界面，你可以看下这个 #102

**Comment by Miao-Mico** [comment]
> > > @Miao-Mico 如果你是在脚本编辑界面点击`调试run`，是不会更新执行时间和执行结果的
> > 
> > 
> > 如果是说 `IDE` 里面 `调试器` 的 `调试` 的话，我没有用过 `IDE` 的调试器，只是在 `VSC` 编辑之后，本地复制上去 `添加脚本`，直接 `F12` 然后点 `立即执行` 那个三角形，看 `Chrome DevTools` 里的 `Console` 栏的输出，其他的我也基本没动过。
> > 我没从事过 `JavaScript` 的开发，不清楚你说的是哪里，也还没找到。
> > 如果可以的话，请赐教。
> 
> 新版本有调试界面，你可以看下这个 #102

我用的市场版的，最近没有发现更新，也没有 `调试run` 这个选项。

**Comment by yi-Xu-0100** [comment]
#102 市场版不更新了，需要自己下载扩展报，相当于 dev 版吧，现在这个仓库的包有无法添加脚本的 bug，可以先用 #102 中的我发的包。

**Comment by Miao-Mico** [comment]
> #102 市场版新版本无法更新，暂时应该是更不了，需要自己下载扩展包，相当于 dev 版吧，现在这个仓库的包有无法添加脚本的 bug，可以先用 #102 中的我发的包。

昂，貌似现在是好了，市场版确实太老了，我一直用的市场版。
不过还是那个问题，域名匹配问题，用的 `*`，调试的时候能通过，保存之后，再运行可以，但是再添加一个域名为 `*` 的，调试不通过，把域名改成 `*.*.*` ，然后保存，运行，然后在运行第一个，就报 `domain配置不正确`。所以到底 `*` 这个是个什么情况啊。

**Comment by yi-Xu-0100** [comment]
不知道，给一下脚本看看吧，如果每个脚本都用 `*.*.*`，会不会好点。

**Comment by Miao-Mico** [comment]
> 不知道，给一下脚本看看吧，如果每个脚本都用 `*.*.*`，会不会好点。

不行啊，有使用二级域名的。

- `*`
https://soulsign.inu1255.cn/script/Miao-Mico/sspanel.js
- `*.*.*`
把 `*` 改成 `*.*.*`，并把其他 `@domain` 去掉
https://soulsign.inu1255.cn/script/Miao-Mico/discuz.js

**Comment by yi-Xu-0100** [comment]
`@domain` 只保留 `*.*.*` 和 `*.*` , 其他的都删了。`*.*` 应该可以匹配二级域名，你的脚本我没法测试，没有相关的网站需要签到

**Comment by Miao-Mico** [comment]
> `@domain` 只保留 `*.*.*` 和 `*.*` , 其他的都删了。`*.*` 应该可以匹配二级域名，你的脚本我没法测试，没有相关的网站需要签到

这个自然可以，不过我就想着不能有一个全匹配的吗，`*` 为啥有时候行呢？

**Comment by yi-Xu-0100** [comment]
运行报啥？@damain 配置不正确？

**Comment by Miao-Mico** [comment]
> 运行报啥？@damain 配置不正确？

对的

**Comment by yi-Xu-0100** [comment]
我这运行，没有报这个问题

![image](https://user-images.githubusercontent.com/25523606/88639159-0ce02a00-d0ef-11ea-8647-55224b74bc66.png)

**Comment by Miao-Mico** [comment]
> 不过还是那个问题，域名匹配问题，用的 *，调试的时候能通过，保存之后，再运行可以，但是再添加一个域名为 * 的，调试不通过，把域名改成 *.*.* ，然后保存，运行，然后在运行第一个，就报 domain配置不正确。所以到底 * 这个是个什么情况啊。

对的，我刚上来也不报错

这是现在的情况

![soulsign](https://user-images.githubusercontent.com/42897857/88640123-28980000-d0f0-11ea-8d12-ced1990cc2ab.gif)

**Comment by yi-Xu-0100** [comment]
我这里复现不出你的状况，我多次尝试调试和直接运行，都是直接通过的。

你还有其他地方的修改嘛？

**Comment by yi-Xu-0100** [comment]
而且，我这边使用脚本会非常卡顿，估计3-5秒才能执行完脚本。不知道是不是判断逻辑的问题

**Comment by Miao-Mico** [comment]
> 我这里复现不出你的状况，我多次尝试调试和直接运行，都是直接通过的。
> 
> 你还有其他地方的修改嘛？

木有了

**Comment by Miao-Mico** [comment]
> 而且，我这边使用脚本会非常卡顿，估计 3-5 秒才能执行完脚本。不知道是不是判断逻辑的问题

这个正常，网站请求可能耗点时间，逻辑判断，`mmc.js` 是我自己写的，我暂时没发现啥问题，你也可以去帮我瞅瞅。

![image](https://user-images.githubusercontent.com/42897857/88641501-e8398180-d0f1-11ea-8c13-8462a009cb3e.png)

**Comment by yi-Xu-0100** [comment]
在出现domain配置不正确的那次运行过程中，network 走到哪个请求你看下，有啥问题没

**Comment by Miao-Mico** [comment]
> 在出现 `domain 配置不正确`的那次运行过程中，network 走到哪个请求你看下，有啥问题没

没动，这个老版本我试验过，你之前也说了，是在 axios 之前卡住的，任何请求都不会发出去。

**Comment by yi-Xu-0100** [comment]
`domain 配置不正确`，只有在实际运行才会出现是嘛？

**Comment by Miao-Mico** [comment]
> `domain 配置不正确`，只有在实际运行才会出现是嘛？

是.

不过我想起来，`mmc.js` 也用的 `*`，升级新版本之后，我原来加载本地脚本的方法失效了（file:///c:/...）。你有其他方法吗?
再一想，为啥调试时候可以的？可能也不是 `mmc.js` 的问题，我先试试改 `mmc.js`

**Comment by yi-Xu-0100** [comment]
我的 network 是这样的。

![image](https://user-images.githubusercontent.com/25523606/88642953-af9aa780-d0f3-11ea-9479-c6f64b4de75b.png)

本地脚本放 GitHub 上就是。

**Comment by Miao-Mico** [comment]
> 本地脚本放 GitHub 上就是。

那多麻烦，我原来都是直接加载本地的，改了，直接可以应用。

![image](https://user-images.githubusercontent.com/42897857/88643256-0d2ef400-d0f4-11ea-9d59-aeed69ebece0.png)

**Comment by yi-Xu-0100** [comment]
运行一下其他的脚本，有相关的网络请求嘛？感觉好像直接就是不执行，开始的判断就不通过。

**Comment by Miao-Mico** [comment]
> 运行一下其他的脚本，有相关的网络请求嘛？感觉好像直接就是不执行，开始的判断就不通过。

`discuz.js` 没问题。
![image](https://user-images.githubusercontent.com/42897857/88644125-297f6080-d0f5-11ea-8d74-7a7ece1cd4ee.png)

**Comment by yi-Xu-0100** [comment]
你确定，你这个版本是签到市场上的那个嘛？仅修改了头部信息，如果用到本地脚本，我这里应该没有本地脚本，是否是本地脚本内有问题。

我测试了下，在脚本中，它是运行到哪，哪里才报错，就是前面的请求如果能执行，network 中是能看到的。当出现不符合的，会报错暂停，除非你的第一条请求就不行。

**Comment by Miao-Mico** [comment]
> 你确定，你这个版本是签到市场上的那个嘛？仅修改了头部信息，如果用到本地脚本，我这里应该没有本地脚本，是否是本地脚本内有问题。
> 
> 我测试了下，在脚本中，它是运行到哪，哪里才报错，就是前面的请求如果能执行，network 中是能看到的。当出现不符合的，会报错暂停，除非你的第一条请求就不行。

原本上的是调的市场里的 `mmc.js`。
我说想改掉本地的，直接改 `sspanel.core` 里的网址，让脚本调用本地的 `mmc.js`。

我这边解决了，是 `mmc.js` 里 `@domain *` 的问题。
`sspenel.js` 的 `axios` 请求写在 `mmc.js` 里面呢，而 `discuz.js` 是写在它自己里面的。

不过还有点不明白为啥我这边 `调试xxx` 可以跑过去而 `立即执行` 跑不过去、你那边可以跑过去？
可不可以有一个代替 `*.*` 和 ‘*.*.*’ 的方式吗，允许所有的类型，既然可以放开，为啥不简单点，比如 '*'。

**Comment by Miao-Mico** [comment]
把这个关上吧，这个 issue 原来的问题，解决了。
