### ISSUE TITLE
怎么 require 本地 js 脚本

### ISSUE THREAD

**Issue by miiwu** [inu1255/soulsign-chrome#104]
原来使用的`市场版 1.1.2`，开了 `允许访问文件网址`，可以通过 `require("file:///C:/xxx.js");` `require` 到本地脚本。
现本地安装 `Github 2.0.6` 并使用后发现方法好像失效了。

有没有别的方法。

**Comment by Miao-Mico** [comment]
windows 建了个 IIS，可以通过 localhost 访问本地脚本了。

可是又有另一个问题，`调试xxx` 和 `立即执行`，运行环境不一样吗？为啥输出不一样呢？
市场版的 `立即执行` 就不会这样，本地改了，就可以马上加载更改。
用惯了市场版，不知新版是特意这样的吗？
![soulsign require](https://user-images.githubusercontent.com/42897857/88751215-b96eea00-d189-11ea-95fb-d119182debfc.gif)

**Comment by inu1255** [comment]
@Miao-Mico 
1. file:///C:/xxx.js请求失败是一个bug，后面会修复
2. 调试界面是直接在options环境执行的，立即执行等是在background环境执行的    
![image](https://user-images.githubusercontent.com/5772409/88771547-fa7af480-d1b1-11ea-9ec6-a590236b3bf0.png)

**Comment by Miao-Mico** [comment]
>调试界面是直接在 options 环境执行的，立即执行等是在 background 环境执行的

那对我这个外行人来说，暂时有点麻烦，`立即执行` 和 `调试xxx` 不一样。
