### ISSUE TITLE
那个 `build.zip` 怎么来的呀？

### ISSUE THREAD

**Issue by miiwu** [inu1255/soulsign-chrome#107]

**Comment by yi-Xu-0100** [comment]
??? 是说怎么编译出来嘛

npm 安装依赖之后，使用 `package.json` 的 `build` 命令去生成。

注意：仓库中的环境应该是 linux 的环境，windows 下会因为没有 `rm` 方法出错。我在我的仓库中添加了一个 `build.js` 并修改了 `package.json` 的 `build` 命令的内容去处理这个问题，仅供参考。

**Comment by Miao-Mico** [comment]
> ??? 是说怎么编译出来嘛
> 
> npm 安装依赖之后，使用 `package.json` 的 `build` 命令去生成。
> 
> 注意：仓库中的环境应该是 linux 的环境，windows 下会因为没有 `rm` 方法出错。我在我的仓库中添加了一个 `build.js` 并修改了 `package.json` 的 `build` 命令的内容去处理这个问题，仅供参考。

扛不住，没开发环境。
我改了点东西，不知道怎么测试。
有没有不用开发者模式加载扩展的调试方法么？这样可能就不用编译了。

**Comment by yi-Xu-0100** [comment]
应该没有……当前扩展需要使用开发环境去生成扩展，最终的扩展和源码形式上不太一样。

**Comment by Miao-Mico** [comment]
> 应该没有…… 当前扩展需要使用开发环境去生成扩展，最终的扩展和源码形式上不太一样。

谢大佬，我还是编译了，哈哈哈
