### ISSUE TITLE
哪位大佬可以做一下威锋网的签到

### ISSUE THREAD

**Issue by skycity233** [inu1255/soulsign-chrome#108]
https://www.feng.com/

**Comment by yi-Xu-0100** [comment]
脚本安装链接: <https://soulsign.inu1255.cn/scripts/235>

其中有个参数，我不确定是否是每个人不同，如果签到成功的话，麻烦关闭 issue 的时候说一声。

**Comment by skycity233** [comment]
> 脚本安装链接: https://soulsign.inu1255.cn/scripts/235
> 
> 其中有个参数，我不确定是否是每个人不同，如果签到成功的话，麻烦关闭 issue 的时候说一声。

可以的，谢谢！

**Comment by yi-Xu-0100** [comment]
因为一直有 cookie 失效的问题，电脑端，关闭浏览器后，大概几分钟，网站登录信息就失效了，我终于实现了账号密码登录方式，脚本应该会自动更新，麻烦试试效果，是否有新的问题。

cookie 方式我保留了，因为账号密码如果不提供的话，这样自己登录也是没问题的，防止提示登录的信息频繁骚扰，我将在线检查频率设为 6 小时。

如果脚本有任何问题，可以到我的 [脚本仓库](https://github.com/yi-Xu-0100/soulsign-scripts) 给我提 issue，如果觉得不错的话，麻烦给个 star。😁

**Comment by skycity233** [comment]
> 因为一直有 cookie 失效的问题，电脑端，关闭浏览器后，大概几分钟，网站登录信息就失效了，我终于实现了账号密码登录方式，脚本应该会自动更新，麻烦试试效果，是否有新的问题。
> 
> cookie 方式我保留了，因为账号密码如果不提供的话，这样自己登录也是没问题的，防止提示登录的信息频繁骚扰，我将在线检查频率设为 6 小时。
> 
> 如果脚本有任何问题，可以到我的 [脚本仓库](https://github.com/yi-Xu-0100/soulsign-scripts) 给我提 issue，如果觉得不错的话，麻烦给个 star。😁

我用着没有出现过cookie失效的问题。🤣

**Comment by yi-Xu-0100** [comment]
emmm，这，我一直关了浏览器，就得重新登录……不纠结，现在直接可以自动登录了。。。😁
