### ISSUE TITLE
无法获取威锋网 favicon

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#112]
当前获取 favicon 的 api 无法获取到威锋网的 icon，如

<http://api.byi.pw/favicon?url=www.feng.com>: ![威锋网](http://api.byi.pw/favicon?url=www.feng.com)

找到了新的 icon 获取 api，官网：<https://favicon.link>

他会给无法获取的地址给予默认 icon，如:

<https://favicon.link/www.feng.com>: ![威锋网](https://favicon.link/www.feng.com)
<https://favicon.link/api.wfdata.club>: ![威锋网](https://favicon.link/api.wfdata.club)
<https://favicon.link/127.0.0.1>: ![127.0.0.1](https://favicon.link/127.0.0.1)

**Comment by miiwu** [comment]
> 当前获取 favicon 的 api 无法获取到威锋网的 icon，如

我这边是有的没的，都不行，不知道我这个是不是网络环境问题，还是 api 炸了。

![image](https://user-images.githubusercontent.com/42897857/90151624-7e8bc980-ddb9-11ea-9d68-96e48a439cd6.png)
![image](https://user-images.githubusercontent.com/42897857/90151795-b6930c80-ddb9-11ea-80a6-3f7b20cd5e05.png)

**Comment by yi-Xu-0100** [comment]
我找到了，chromium 内核浏览器获取 favicon 的 api，它会获取本地的缓存，如果打开过网页，就可以获取到 favicon，如果没有打开过相关的网页，也会给予浏览器指定的默认图标。

当前已测试过的 chromium 内核浏览器：谷歌浏览器，edge 浏览器，qq 浏览器，联想浏览器。

不同浏览器，会将该地址自动解析到对应浏览器的 api 上，目前看，这样不会因为获取 favicon 的 api 失效，造成显示问题。

详见 #113 的改动。
