### ISSUE TITLE
检查在线能否在成功执行之后关闭？

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#114]
1. 检查在线会按照时间间隔进行，但是脚本运行成功后不会运行，过多的检查在线是否应该更换为脚本运行成功后，则不再检查在线，直到第二天重新检查。
2. 威锋网是使用 websocket 连接方式，cookie 的时效很短，造成关闭浏览器一段时间，打开会处于不在线的方式，如果是按照时间间隔方式检查在线，十分容易造成该网站登录信息失效，不知道如何解决。
3. 我本想通过模拟登录的方式去避免威锋网的登录失效问题，但是好像它是 api 方式，造成我信息返回成功，有相应的用户信息，但是查看网页还是没有登录，我试着设置 header 中的 set-cookie 方式，没有效果

**Comment by inu1255** [comment]
@yi-Xu-0100 
执行成功后仍然会检查是否在线的原因是：有一些网站每次访问会刷新cookie有效时间
1. 如果你的问题是检查间隔过短，可以通过
`@expire            会话过期时间(毫秒),系统会隔一段时间调用一次check接口检查在线状态并保持会话活跃`
2. 如果你的问题是检查是否在线会导致会话失效，那么可以通过check函数直接返回true跳过会话检查

**Comment by yi-Xu-0100** [comment]
这个威锋网在我这的 cookie 时间极短， 可能关了浏览器，1分钟后就失效了。

看来我只能指定检查时间为 6 个小时，这样应该能够提醒到，尽量减少打扰。

不太懂这网站的 cookie 为啥这么短，不知道是不是我的请求的参数问题。

但是我有试过关闭脚本观察该网站的情况，貌似就是这么短，有点奇怪。

暂时先这样吧，感觉没啥好的办法，对于这种次次需要登录的。
