### ISSUE TITLE
请求添加迅维网的签到

### ISSUE THREAD

**Issue by dai640** [inu1255/soulsign-chrome#115]
这个是电脑维修类型的论坛，在同类型论坛中应该是做得比较好的了，无论是人气还是行业人员，很多维修行业的高手也都在论坛里面交流相关的心得与经验，论坛的附件下载需要下载分，下载分可以通过发表主题原创，上传附件，帖子加精华等方式获取，也可以通过RMB充值，1元=1下载分，每天签到可以随机获取1-6分左右吧。

PS：这个比较适合行业人员，很多维修资料以附件形成上传，大部分的附件资料也都比较有价值。

附上论坛链接：https://www.chinafix.com/forum.php

**Comment by yi-Xu-0100** [comment]
因为类似论坛有做过，所以很快，安装链接：<https://soulsign.inu1255.cn/scripts/238>

我注册了，但是需要付费才能签到发帖，暂时没法测试。
如果测试成功，请尝试 **重复执行**，**未登录执行**等方式验证结果是否如预期。
麻烦关闭 issue 的时候告诉一声。

**Comment by dai640** [comment]
测试了，脚本是成功的，感谢大佬！

问题解决！
