### ISSUE TITLE
恩山论坛need fix

### ISSUE THREAD

**Issue by dai640** [inu1255/soulsign-chrome#119]
domain配置不正确，好像挺长时间了，望大侠修复一下。

**Comment by miiwu** [comment]
> 确实，我也没找到签到入口，是不是变成每天登陆自动获取奖励了？

不清楚，我没有账号。

也可能是取消了。

**Comment by dai640** [comment]
终于有大侠帮忙修复了。

[https://soulsign.inu1255.cn/scripts/262](url)
