### ISSUE TITLE
新的 `package.json`，本地修改然后编译，修改应用不上

### ISSUE THREAD

**Issue by miiwu** [inu1255/soulsign-chrome#121]

**Comment by inu1255** [comment]
### 你是说修改后`npm run build`重新加载没有生效吗？   
如果本地开发的话不要用`npm run build-update`生成的包，这个包只会从服务器上更新（重新加载不会生效）；
解决方法：删除插件，重新安装`npm start`/`npm run build`生成的包
### 如果是`npm start`修改没有自动刷新
我新提交的版本修复了这个问题，更新一下就可以了

**Comment by miiwu** [comment]
> ### 你是说修改后 `npm run build` 重新加载没有生效吗？

是这个

- - -

 那我试试

**Comment by miiwu** [comment]
暂时没再出现问题了
