### ISSUE TITLE
关于插件模拟登录

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#123]
@inu1255 ,作者大大，我最近在尝试模拟登录，一些普通的网站还行，请求携带的参数没有加密。

但是如果是前端处理后的数据，有时和时间相关，造成每次的请求携带参数不同，我无法模拟这个登录过程。

我没找到相关的资料说明 js 是否有后台加载页面并模拟点击的方式，这样就绕过了计算参数的过程。

或者有什么其他方法，对这种情况进行模拟吗？我只能找到模拟点击的方法，对相关知识不太了解，也不知道该用什么关键词去查询这个问题。

**Comment by inu1255** [comment]
@yi-Xu-0100 新版本已支持，参见[模拟点击](https://github.com/inu1255/soulsign-chrome#%E6%A8%A1%E6%8B%9F%E7%82%B9%E5%87%BB)

**Comment by yi-Xu-0100** [comment]
非常感谢~
