### ISSUE TITLE
求支持 51nb论坛

### ISSUE THREAD

**Issue by jsxyhyj** [inu1255/soulsign-chrome#126]
https://forum.51nb.com/forum.php

**Comment by yi-Xu-0100** [comment]
可以安装测试：https://soulsign.inu1255.cn/scripts/248

**Comment by jsxyhyj** [comment]
好的，谢谢。明天测试，今天已经手动签到过了。

**Comment by yi-Xu-0100** [comment]
我升级了下脚本，如果明天有报错，可以更新脚本试试，如果还是有问题可以去我的脚本仓库提 issue，喜欢的话，给个 star~😘

仓库地址：https://github.com/yi-Xu-0100/soulsign-scripts

**Comment by yi-Xu-0100** [comment]
@jsxyhyj 可关闭此 issue
