### ISSUE TITLE
`npm run build` 创建的压缩包，仍然会自动更新

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#128]
我昨天测试的没有问题，所以就想先使用着原先的包，但是今天发现，他好像自动更新了。

造成我无法使用我自己更新的版本。我点击重新加载也没有效果……

emmm，不知道咋整

**Comment by yi-Xu-0100** [comment]
主要是以前删除的路径不对，造成生成文件以覆盖方式。

而 update 引入的升级文件，一直无法被删除。

**Comment by yi-Xu-0100** [comment]
我发现浏览器中的插件还是会调用缓存，造成只有删除那个插件，重新添加文件夹才行。

猜测浏览器的重新添加，也只是覆盖文件。造成原来的部分文件不会删除。

**Comment by inu1255** [comment]
![image](https://user-images.githubusercontent.com/5772409/92355127-39d42380-f116-11ea-8d88-b35b8b414327.png)
把这个service-worker unregister之后再重新加载就可以了

**Comment by yi-Xu-0100** [comment]
@inu1255 感谢，可以看下我提交的 pull request，修复了无法未成功删除 build 内文件的问题和模拟点击的的窗口会被置顶的问题。#124 有关于模拟点击的问题的说明。😉

**Comment by yi-Xu-0100** [comment]
@inu1255 虽然现在的 pull 中的解决方案仍然是创建窗口的方式，但是能够最小化，打扰很少了。

至于创建 tab 的方式，得等我后期有空再弄和测试了，非常感谢作者大大的示例~😊
