### ISSUE TITLE
求支持比特球云盘签到

### ISSUE THREAD

**Issue by auauauto** [inu1255/soulsign-chrome#131]
地址：pan.bitqiu.com

可以麻烦大佬花一点时间做一下这个签到脚本吗？

**Comment by yi-Xu-0100** [comment]
比特球云盘：<https://soulsign.inu1255.cn/scripts/251>
可以同时签到的盛天网络：<https://soulsign.inu1255.cn/scripts/252>

有问题可以到 [我的脚本仓库](https://github.com/yi-Xu-0100/soulsign-scripts) 反馈~喜欢的话，给个 star！😜

**Comment by auauauto** [comment]
十分感谢，已点star💕😊

yi_Xu <notifications@github.com> 于2020年9月14日周一 上午8:57写道：
