### ISSUE TITLE
无法捕获脚本内部语法错误

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#132]
脚本内由于内容设置错误，报错，但是并没有日志，不应该是同样的 throw 出来吗？为什么日志出无法捕获？而必须去 console 中查看？

``` bash
TypeError: Cannot read property '1' of null
```

例如上面的错误：匹配结果没匹配到，后续语句对匹配结果进行读取，造成问题，但好像没有被日志捕获，造成 NO_SUMMARY 的反馈，因为是正常签到了，第二次脚本不会对此报错（不需要匹配这句），所以我只能等待第二天自行测试中打开 console 观察，不知道这样的报错是否是未捕获的 bug ？

**Comment by inu1255** [comment]
已修复 @yi-Xu-0100
