### ISSUE TITLE
dependabot 提交过多的 pull request

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#139]
我看到 pull request 提交过多的 pull request，应该是我引入的自动检测 npm包更新造成的。
我同时设置了 GitHub action 的检测更新，这个我忘记说明了，可能造成冲突和困扰。
文件见： <https://github.com/inu1255/soulsign-chrome/blob/master/.github/dependabot.yml>

根据这个文章：<https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/>
我看到好像以前仓库已经存在相应的检测，好像只是检测安全性的依赖问题。
而我引入的好像是同步所有可能的更新，这是我以前不知道的区别，一直以为是一样的，非常抱歉引入这一点😥。
如果不需要这种同步更新的方式，可以删除 npm 包检测更新的部分。

**Comment by inu1255** [comment]
确实以前有安全性检测，我觉得足够了，所以删除 npm 包检测更新的部分
