### ISSUE TITLE
张大妈脚本失效

### ISSUE THREAD

**Issue by isnowify** [inu1255/soulsign-chrome#14]
RT,SMZDM的签到在大概两个星期前失效了…有时间的话麻烦修复一下呀

**Comment by inu1255** [comment]
我这边好像没有问题，能详细描述一下吗

**Comment by jdwsxs** [comment]
大概在今年一月底就失效了  现象是在chrome内正常登录smzdm，但是魂签依旧标注：未登录 手动执行后签到失败
可能smzdm在最近修改了签到API

**Comment by satanickiss** [comment]
firefox 已登陆，签到失败。
