### ISSUE TITLE
模拟点击失败未关闭窗口

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#140]
使用模拟点击的脚本，如果使用 `click()` 函数而选择器不对时，打开的窗口页面不会关闭。

可以使用阿里云脚本测试，将 `click()` 函数中的选择器字符串改成不存在的标签值即可。

我发现虽然窗口不会关闭，但是过了一段时间，仍然会判断处不在线，然后再次验证时，会打开新的窗口。这里如果脚本有误，容易造成打开多个窗口。

**Comment by inu1255** [comment]
不关闭的原因是脚本被`fb.waitLoaded()`阻塞了，`waitLoaded` 会等待页面加载完成才返回；
`waitLoaded(timeout)`支持超时参数。加上超时参数脚本应该就不容易打开多个窗口了

**Comment by yi-Xu-0100** [comment]
加了超时参数，避免了阻塞问题，也会关闭页面了，但是会往后进行，造成返回 `true` ，我不知道怎么让他返回个布尔值以便让`check` 不通过。

``` js
if (fb.url.startsWith("https://register.stnts.com/new/v2/login.do")) {
	await fb.click(".btn.btn-blue.btn-max.mt30.js-auto-submit-bt");
	//故意末尾少n，模拟获取错误。
	//因为该网站登录有时是有缓存的，如果是退出登录，该界面会要求输入账户密码，页面应该不同，我暂时没有适配。
	await fb.waitLoaded(1e3);
	return true;
}
```

我看到在 `openTab` 中有调用到 `waitLoaded()`（下面截取源码部分），如果直接修改设置并添加更多的返回值，感觉肯定会有影响。

``` js
pms.then(() => frameRunner(tab.id, 0, domains, url))
						.then((x) => x.waitLoaded().then(() => x))
						.then(fn)
						.then(resolve, reject)
						.finally(() => chrome.tabs.remove(tab.id));
```

**Comment by inu1255** [comment]
`click` 如果超时元素不存在，会返回false
下个版本给`waitLoaded`一个默认超时参数，并增加返回值

**Comment by yi-Xu-0100** [comment]
> `click` 如果超时元素不存在，会返回false

我验证了一下，好像可以，非常感谢，判断上没有问题了。
