### ISSUE TITLE
求个漫画补档网站的签到脚本

### ISSUE THREAD

**Issue by iErics** [inu1255/soulsign-chrome#142]
求哪位大佬发一个漫画补档网站的签到脚本，网址是：https://www.manhuabudang.com/

**Comment by yi-Xu-0100** [comment]
我制作了签到脚本，并发布了，见：<https://soulsign.inu1255.cn/scripts/266>

个人验证无误，如果成功签到，可以关闭这个 issue ~

如果我的脚本内容触发了问题，可以去我的 [脚本仓库](https://github.com/yi-Xu-0100/soulsign-scripts/) 提 issue ，如果我的脚本有帮助，喜欢的话点个 star ~😘

**Comment by iErics** [comment]
> 我制作了签到脚本，并发布了，见：https://soulsign.inu1255.cn/scripts/266
> 
> 个人验证无误，如果成功签到，可以关闭这个 issue ~
> 
> 如果我的脚本内容触发了问题，可以去我的 [脚本仓库](https://github.com/yi-Xu-0100/soulsign-scripts/) 提 issue ，如果我的脚本有帮助，喜欢的话点个 star ~😘

谢谢大佬，已Star

**Comment by yi-Xu-0100** [comment]
@iErics 检查在线逻辑有点问题，已修复升级，如果有报错，可以尝试先更新脚本到 v1.0.2

还是有问题，可以去可以去我的 [脚本仓库](https://github.com/yi-Xu-0100/soulsign-scripts/) 提 issue~😁
