### ISSUE TITLE
geekhub出错error 422

### ISSUE THREAD

**Issue by auauauto** [inu1255/soulsign-chrome#143]
已经在geekhub登录了，但依旧显示这个错误
`{ "message": "Request failed with status code 422", "name": "Error", "stack": "Error: Request failed with status code 422\n at createError (webpack-internal:///FtD3:16:15)\n at settle (webpack-internal:///21It:17:12)\n at XMLHttpRequest.handleLoad (webpack-internal:///7GwW:61:7)", "config": { "url": "https://geekhub.com/checkins", "method": "post", "headers": { "Accept": "application/json, text/plain, */*" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 10000, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 } }`

**Comment by yi-Xu-0100** [comment]
你好，你使用的是哪个脚本，我个人制作的geekhub脚本是： <https://soulsign.inu1255.cn/scripts/172>

个人签到一直没有问题的。

**Comment by yi-Xu-0100** [comment]
如果你的报错是我的脚本，可以去我的[脚本仓库](https://github.com/yi-Xu-0100/soulsign-scripts)提 issue，暂时关闭这个 issue ，以便不打扰这个插件仓库。如果我的脚本能够给予帮助，喜欢的话给个 star~😁

**Comment by auauauto** [comment]
好的，我使用的另一个人的脚本，不成功。使用你的脚本没有问题。我已经关闭了issue并点了star。非常感谢你的帮助

yi_Xu <notifications@github.com> 于2020年9月23日周三 上午9:36写道：
