### ISSUE TITLE
Firefox安装MMC脚本失败

### ISSUE THREAD

**Issue by xinyannp** [inu1255/soulsign-chrome#144]
https://soulsign.inu1255.cn/scripts/218

安装时，错误提示“脚本需要run/check函数”

**Comment by yi-Xu-0100** [comment]
应该不是直接使用 mmc ，应该使用相关的聚合脚本，<https://soulsign.inu1255.cn/?uid=1178>

![image](https://user-images.githubusercontent.com/25523606/93991150-89754900-fdbe-11ea-9910-dc50d3e05364.png)

类似这些，具体，需要 @miiwu 讲解，可以去 [聚合脚本仓库](https://github.com/miiwu/sspanel.soulsign) 看相关说明，该作者的发布账户和GitHub账户不一致，但一直我们 GitHub 上有交流。

**Comment by xinyannp** [comment]
> 
> 
> 应该不是直接使用 mmc ，应该使用相关的聚合脚本，https://soulsign.inu1255.cn/?uid=1178
> 
> ![image](https://user-images.githubusercontent.com/25523606/93991150-89754900-fdbe-11ea-9910-dc50d3e05364.png)
> 
> 类似这些，具体，需要 @miiwu 讲解，可以去 [聚合脚本仓库](https://github.com/miiwu/sspanel.soulsign) 看相关说明，该作者的发布账户和GitHub账户不一致，但一直我们 GitHub 上有交流。

直接使用聚合脚本（https://soulsign.inu1255.cn/scripts/230），运行也报错 “ReferenceError: tools is not defined ”，不知道是配置问题还是其他问题。
配置项也找不到范例，不知道填写的是不是正确的。

**Comment by yi-Xu-0100** [comment]
不知道你具体是要签到哪个网站，可以搜索域名或者名称看看有没有相关的脚本已经发布了。或者直接翻页看看

**Comment by inu1255** [comment]
@xinyannp 你是否使用的firefox扩展商店安装的?那里的版本很久没有更新了，我刚刚更新了，你可以更新一下再试试

**Comment by xinyannp** [comment]
@inu1255 更新后可以使用了，赞美~
本来准备用来给国内PT站签到的，但是很多站都搞了个性化签到系统，还基本都有机器人验证，导致用不上╮(╯﹏╰）╭。

**Comment by miiwu** [comment]
@xinyannp 
我刚看到。
大佬用的哪个脚本签到成功 pt站 的呀?
我没有账号，没法测试[pt站可能的框架](https://soulsign.inu1255.cn/scripts/226) 整合脚本的正确性。

**Comment by miiwu** [comment]
> 直接使用聚合脚本（https://soulsign.inu1255.cn/scripts/230），运行也报错 “ReferenceError: tools is not defined ”，不知道是配置问题还是其他问题。

这个链接好像无法访问呀。

> 配置项也找不到范例，不知道填写的是不是正确的。

这个的话，每个集合脚本介绍页面应该有文字叙述;
我可能得改改配置页面的提示了。
下次在添加个图片看看？
