### ISSUE TITLE
求个优矿论坛的签到脚本

### ISSUE THREAD

**Issue by baofengqqwwff** [inu1255/soulsign-chrome#145]
如题，不是很懂写，能否帮忙写个优矿论坛的签到脚本？签到页面是https://uqer.datayes.com/v3/community/list，谢谢大佬

**Comment by yi-Xu-0100** [comment]
我制作了签到脚本，并发布了，见：<https://soulsign.inu1255.cn/scripts/268>

个人验证无误，如果成功签到，可以关闭这个 issue ~

如果我的脚本内容触发了问题，可以去我的 [脚本仓库](https://github.com/yi-Xu-0100/soulsign-scripts/) 提 issue ，如果我的脚本有帮助，喜欢的话点个 star ~😘

**Comment by inu1255** [comment]
https://github.com/inu1255/soulsign-chrome/issues/309
