### ISSUE TITLE
别人的超话签到脚本，知道哪里有问题，麻烦大佬看一下

### ISSUE THREAD

**Issue by wangshiw** [inu1255/soulsign-chrome#148]
// ==UserScript==
// @name              微博超话签到
// @version           1.0.0
// @author            sukura
// @loginURL          https://weibo.com
// @expire            900000
// @domain            weibo.com
// ==/UserScript==

exports.run = async function(param) {
    var res = await axios.get('https://weibo.com/p/aj/general/button', {
    	params: {
    		ajwvr: 6,
    		api: 'http://i.huati.weibo.com/aj/super/checkin', {
    		ID: '100808b488b29a2e80ec84a3dca10c59cd6996'
    		location: 'page_100808_super_index',
    		timezone: 'GMT+0800',
    		lang: 'zh-CN,zh;q=0.9',
    		plat: 'Win32' ,
    		ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36',
    		screen: '1366*768',
    		__rnd: '1601385918908'
    	}
    	headres: { 'Referer': 'https://weibo.com' }
    });

    if (res.status != 200) throw '需要登录';
    var { code, msg, data } = res.data;
    if (code == 10000) {
    	var { alert_title, alert_subtitle } = data;
    	return '' +alert_title +alert_subtitle;
    }
    if (code -- 382004) {
        return '今天已签到';
    }
    throw msg;
 };

exports.check = async function(param) {
    var res = await axios.get('https://weibo.cpm/p/aj/general/button', {
    	params: {
    		ajwvr: 6,
    		api: 'http://i.huati.weibo.com/aj/super/checkin',
    		id: '100808b488b29a2e80ec84a3dca10c59cd6996',
    		location: 'page_100808_super_index',
    		timezone: 'GMT 0800',
    		lang: 'zh-CN,zh;q=0.9',
    		plat: 'Win32',
    		ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36',
    		screen: '1366*768',
    		__rnd: '1601385918908'
    	},
    	headres: { 'Referer': 'https://weibo.com' }
    });
    return res.status == 200;
};

**Comment by yi-Xu-0100** [comment]
@wangshiw 如果可以，使用 markdown 中代码块语法将整个脚本的内容包裹。

```
// ==UserScript==
// @name 微博超话签到
// @version 1.0.0
// @author sukura
// @loginurl https://weibo.com
// @expire 900000
// @domain weibo.com
// ==/UserScript==
```

这里关键词应该是大小写敏感的。更多的见 [脚本开发](https://github.com/inu1255/soulsign-chrome#%E8%84%9A%E6%9C%AC%E5%BC%80%E5%8F%91)
