### ISSUE TITLE
立创eda签到

### ISSUE THREAD

**Issue by TCNOV16** [inu1255/soulsign-chrome#156]
// ==UserScript==
// @name              立创eda
// @namespace         https://github.com/inu1255/soulsign-chrom
// @version           1.0.0
// @author            none
// @loginURL         https://oshwhub.com/sign_in   
// @expire            900000
// @domain            oshwhub.com
// ==/UserScript==

exports.run = async function () {
     let resp = await axios.get("https://oshwhub.com/sign_in");
    let signhtml = resp.data;
    if (signhtml.includes("已签到"))
        return "已签到";
    else return "未签到"

};

exports.check = async function () {
    var { data } = await axios.get('https://oshwhub.com/');
    return !(/GUser={}/.test(data));
};

知道是 await axios.get的问题，但确实不懂该换成哪个链接，上面是直接查询网页字符，切换账号测试确实是有效的，努力过了，求大佬改改

**Comment by yi-Xu-0100** [comment]
1. 评论支持 markdown，代码最好放在 markdown 的代码块中。
2. run 中流程应该是请求对应签到的链接，如果签到的请求需要一些参数，也需要附上，在 #70 中有着部分制作过程的讨论，可以了解一下。

**Comment by TCNOV16** [comment]
`// ==UserScript==
// @name              立创eda
// @namespace         https://github.com/inu1255/soulsign-chrom
// @version           1.0.0
// @author            zws
// @loginURL         https://oshwhub.com/sign_in   
// @expire            900000
// @domain            oshwhub.com
// ==/UserScript==

exports.run = async function () {

var { data } = await axios.post('https://oshwhub.com/api/user/sign_in');
    if (data.code == 200) 
        return '打卡成功';

    let resp  = await axios.get("https://oshwhub.com/sign_in");
  let signhtml = resp.data;
   if (signhtml.includes("已签到"))
      return "老色批已签到"
else return "老色批未签到"
};




exports.check = async function () {
    var { data } = await axios.get('https://oshwhub.com/');
    return !(/GUser={}/.test(data));
};`

emm ok

**Comment by TCNOV16** [comment]
`// ==UserScript==
// @name              立创eda
// @namespace         https://github.com/inu1255/soulsign-chrom
// @version           1.0.0
// @author            zws
// @loginURL         https://oshwhub.com/sign_in   
// @expire            900000
// @domain            oshwhub.com
// ==/UserScript==

exports.run = async function () {

var { data } = await axios.post('https://oshwhub.com/api/user/sign_in');
    if (data.code == 200) 
        return '打卡成功';

    let resp  = await axios.get("https://oshwhub.com/sign_in");
  let signhtml = resp.data;
   if (signhtml.includes("已签到"))
      return "老色批已签到"
else return "老色批未签到"
};




exports.check = async function () {
    var { data } = await axios.get('https://oshwhub.com/');
    return !(/GUser={}/.test(data));
};`

**Comment by TCNOV16** [comment]
post的话就没有后面的判断才对，直接发送请求就行了
