### ISSUE TITLE
v2ex 的签到脚本会导致网页登录 v2ex 的时候一直提示验证码错误

### ISSUE THREAD

**Issue by JackieMium** [inu1255/soulsign-chrome#16]
具体表现就是用了一阵子之后 v2ex 自动登录会失效，然后手动登录会一直提示验证码失败。只要一关上魂签里的 v2ex 的脚本然后 Shift + F5 强制刷新页面再输入正确的验证码就可以登录成功。

这个问题已经是第二次出现，上次关掉很多拓展才登录上去不知道到底是谁的问题。今天只关掉魂签就可以，证明就是魂签的问题。

**Comment by inu1255** [comment]
bug原因: v2ex脚本检查是否在线使用这个链接 https://www.v2ex.com/mission/daily，当你不在线时这个链接会发生302跳转到登录界面(这会导致验证码图片被刷新)；
bug修复: 修改检查是否在线的链接
把v2ex脚本更新到1.0.2就可以了
