### ISSUE TITLE
浏览器自动删除插件

### ISSUE THREAD

**Issue by lvlvlvlvlvlv** [inu1255/soulsign-chrome#160]
浏览器自动删除插件，这个怎么操作呢

**Comment by yi-Xu-0100** [comment]
@lvlvlvlvlvlv 没太懂你的描述，有什么提示没，是否是完全删除，需要重新安装？

**Comment by makson5** [comment]
我是下载的2.42手动安装的，每隔1个礼拜左右，魂签就自动消失了，必须重新手动安装一次才行，不知道其他人是不是这样。

**Comment by yi-Xu-0100** [comment]
@makson5 什么浏览器什么版本？我这边是 edge dev 没有这个问题。不是 dev 的话，会提示开发者选项的问题，所以就换了 dev

**Comment by makson5** [comment]
我用的是Chrome 88.0.4324.146 64位

**Comment by 1ninty2** [comment]
我也出现了这个问题，用着好好的突然就不见了

**Comment by yi-Xu-0100** [comment]
google 插件的安全机制……没什么好地解决版本，试试开发者模式，加载本地文件。不行，试试 edge dev 吧。
