### ISSUE TITLE
吾爱破解签到失效了，即使登录了还是显示不在线

### ISSUE THREAD

**Issue by auauauto** [inu1255/soulsign-chrome#165]
执行结果是
Error: Request failed
with status code 403

我已经登录了，但还是显示不在线

**Comment by yi-Xu-0100** [comment]
@auauauto 给出脚本链接，推荐中有重名脚本，无法确定你说的是哪一个

**Comment by auauauto** [comment]
大佬你好，吾爱破解有三个脚本，我刚刚每个都试了试，都不行，而且三个都显示一样的错误。不知是不是今天吾爱破解网站技术人员作了调整。
这里顺便回复一下你的爱奇艺的邮件。我确实是1.0.4版本喔，而且你看看图片，并没有显示不在线，但就是不知为什么失败。
[image: 1.png]

yi_Xu <notifications@github.com> 于2020年11月11日周三 下午1:30写道：

**Comment by yi-Xu-0100** [comment]
@auauauto 图片没有看到，如果可以，建议在 GitHub 发一下，如果可以，运行脚本的时候，打开控制台，将控制台的红色报错信息发给我，如果你了解的话，将 network 中运行到哪一个了发一下，是只进行第一个任务就出错结束了，还是到第几个。

爱奇艺的签到脚本最近刚做，一天一次的测试中，可能有问题，如果明天我找到问题的话，我会更新下，到时候你再试下

**Comment by yi-Xu-0100** [comment]
吾爱破解的话，我就不知道具体情况了，没有相应的账户，以前申请过，不活跃被删了

**Comment by auauauto** [comment]
老哥不好意思，可能我网络问题，在GitHub上传不了图片，我刚刚上传了图床，麻烦你帮我看看这个错误是怎么回事。
https://imgurl.cloudimg.cc/2020/11/11/a2e9f1111092241.jpg

yi_Xu <notifications@github.com> 于2020年11月11日周三 下午7:02写道：

**Comment by yi-Xu-0100** [comment]
@auauauto 我不太确定，明天看看问题出在哪里，再更新一般吧，你可以去 会员签到 那里看看，应该会员的签到部分成功了，但是后面获取积分部分失败了

**Comment by auauauto** [comment]
今日恢复正常了。就仅仅是昨天和前天有问题

yi_Xu <notifications@github.com> 于2020年11月11日周三 下午9:30写道：

**Comment by auauauto** [comment]
感谢你对我的提问的关注与帮助

Yu Hao <chenyuhao0304@gmail.com> 于2020年11月12日周四 下午9:31写道：
