### ISSUE TITLE
请问录制脚本要怎么操作

### ISSUE THREAD

**Issue by lancer-wang** [inu1255/soulsign-chrome#166]
求出个教程

**Comment by inu1255** [comment]
@lancer-wang 
1. 打开魂签任务管理界面，点击录制脚本按钮
2. 输入目标网址，如：https://www.baidu.com/ 点击确定
3. 魂签会打开目标网站，等待录制程序启动完成后会弹出“点击确定开始录制, 切换回魂签界面结束录制”
4. 点击确定，并进行操作（如：输入`魂签`点击搜索），魂签会把你在网页中的点击、输入框输入录制下来
5. 录制完成后切换回魂签任务管理标签页，此时魂签会根据刚刚录制的操作生成脚本并打开添加脚本窗口
6. 你可以把代码中的 `/** 调试时设置成true */ false` 修改为`true`然后点击【调试run】来测试脚本运行效果

实现原理：通过在目标页面注入js来监听鼠标和输入事件，并生成相应的脚本代码。
生成的签到脚本只是简单地重复它监听到的操作，并没有高级的逻辑判断，所以目前能实现的功能比较单一（比如打开目标网站，点击签到按钮 或 打开目标网站输入账号密码并登录），如果需要根据是否在线进行不同的操作，需要自行修改代码逻辑。

目前功能初步实现，可能存在较多bug，如果遇到烦请告知。

**Comment by lancer-wang** [comment]
多谢,要用的网站今天签到过了,明天测试一下

**Comment by lancer-wang** [comment]
实测可以使用
