### ISSUE TITLE
吾爱破解论坛签到bug

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#17]
我的吾爱破解论坛签到总是提示不在线（其实是在线的），然而任务还是自动做了的，就是提示不在线，是不是检测在线状态有点问题，不知道怎么调查相关的错误，感谢作者制作！

**Comment by inu1255** [comment]
点击编辑按钮，可以查看对应的代码； `exports.check` 对应的是检查是否在线的代码；如：
``` javascript
exports.check = async function() {
    var { status, data } = await axios.get('https://www.52pojie.cn/home.php?mod=task&do=apply&id=2', { maxRedirects: 0 });
    return status == 302 || /本期您已申请过此任务/.test(data);
};
```
这段代码在我这边测试是可以判断是否在线的

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/54888484-6a031480-4ed8-11e9-9398-772a1444956f.png)
![image](https://user-images.githubusercontent.com/25523606/54888496-7edfa800-4ed8-11e9-87dd-976924315e3f.png)
有这个代码，很奇怪

**Comment by kifast** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/54888484-6a031480-4ed8-11e9-9398-772a1444956f.png)
> ![image](https://user-images.githubusercontent.com/25523606/54888496-7edfa800-4ed8-11e9-87dd-976924315e3f.png)
> 有这个代码，很奇怪

你应该F12 后, 把签到后包文拿出来看一下, 这样就很好解决问题了

**Comment by yi-Xu-0100** [comment]
嗯……刚刚看了下，又好了，我没法复现这个问题，可能是**点击现在执行没法重新检测登录状态**。
我的网络是连接后，需要浏览器跳转登录，我打开，这个时候就会有一些提醒，表示我没有在线。
一般提示的都是我脚本列表中的miui论坛，但是我登录网络后，重启浏览器，一般都会签到成功。
早上的时候，刷了一小会，发现这个吾爱破解还是显示不在线，就点了那个运行按钮，**应该就签到成功了，但是登录状态没有刷新**，这个登录状态的检测不应该在执行脚本的开始嘛？

**Comment by yi-Xu-0100** [comment]
> > ![image](https://user-images.githubusercontent.com/25523606/54888484-6a031480-4ed8-11e9-9398-772a1444956f.png)
> > ![image](https://user-images.githubusercontent.com/25523606/54888496-7edfa800-4ed8-11e9-87dd-976924315e3f.png)
> > 有这个代码，很奇怪
> 
> 你应该F12 后, 把签到后包文拿出来看一下, 这样就很好解决问题了

比较小白，没太懂拿什么包，我在吾爱破解网页，F12没看到什么报错，在魂签管理界面，F12，也没有任何的报错，能指导一下去哪找相关的log吗？
