### ISSUE TITLE
CHROME下扩展自动消失

### ISSUE THREAD

**Issue by kanjianjiuhao** [inu1255/soulsign-chrome#170]
CHROME v86.0.4240.75
魂签 v2.4.2
今天出现魂签扩展自动消失的现象，在设置下，扩展程序页面找不到。
手动下载build_v2.4.2才恢复，自己录制的脚本也在
平时都只使用休眠主机，CHROME一直打开不会关闭
请问这种情况我以后应该注意什么？

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 是否是下载的解压后的安装文件夹被删除？

**Comment by kanjianjiuhao** [comment]
> @kanjianjiuhao 是否是下载的解压后的安装文件夹被删除？

下载build ZIP文件夹，解压在E盘，然后在CHROME里安装，再删除了E盘下的文件夹。这样应该不会影响吧？
再次安装后，自己设置的扩展数据都在

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 不要删除安装地址对应的文件夹，chrome好像是定期检查那个文件夹的，建议保留。

**Comment by kanjianjiuhao** [comment]
> @kanjianjiuhao 不要删除安装地址对应的文件夹，chrome好像是定期检查那个文件夹的，建议保留。

好的，我再试试。
刚才又删除了新下载的build 文件夹，CHROME上的魂签扩展并没有马上消失，再看看这几天是否会被影响。
另外请问，以后要更换CHROME，是否直接备份扩展的ID名文件夹的同时，也要备份下载解压的这个build文件夹？

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 我认为解压安装的插件应该不会被同步，不同地址或者不同电脑安装后的 id 应该也不同，建议使用插件中的页面导出配置（我是这样的）。安装包的话，可以备份，也可以重新从这里下载安装。

**Comment by kanjianjiuhao** [comment]
> @kanjianjiuhao 我认为解压安装的插件应该不会被同步，不同地址或者不同电脑安装后的 id 应该也不同，建议使用插件中的页面导出配置（我是这样的）。安装包的话，可以备份，也可以重新从这里下载安装。

明白了，谢谢回复。直接使用导出功能备份更好！
也很多谢分享的好扩展，解决了许多问题，祝下午愉快！
