### ISSUE TITLE
chrome

### ISSUE THREAD

**Issue by wanghaisheng** [inu1255/soulsign-chrome#171]
'''
网址为 chrome-extension://icgicbmfmmjmoljmahipcnmabajooind/pages/popup.html 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
'''

**Comment by yi-Xu-0100** [comment]
如果是商店安装版，建议下载压缩包安装开发者版。
如果是开发者版，看看是否和 #170 一样，修改了安装内容。

**Comment by inu1255** [comment]
可能是新版本设置页面变化导致的(之前是 /pages/options.html 现在是 /options.html)，发了个 2.5.2 版本修复
