### ISSUE TITLE
[建议]鉴于有人已经开发了会有很长链接的批量签到脚本

### ISSUE THREAD

**Issue by whyjxz14** [inu1255/soulsign-chrome#172]
是不是应该把齿轮弹出的框改的大一点，然后把input改成自动换行

**Comment by miiwu** [comment]
> 是不是应该把齿轮弹出的框改的大一点，然后把 input 改成自动换行

嘿，我也有这个想法，23333；

**Comment by inu1255** [comment]
参数配置页面增加了全屏按钮，input支持输入换行，暂不能自动换行哈
