### ISSUE TITLE
在魂签界面刷新会需要加载很久

### ISSUE THREAD

**Issue by kanjianjiuhao** [inu1255/soulsign-chrome#175]
最近发现有脚本运行延时的问题
在CHROME进入到魂签扩展的选项界面时，有时要加载很久才会打开
在这个界面按F5刷新，也会需要很久转圈才正常
CHROME:87.0.4280.66（正式版本） （64 位）
魂签:2.4.2

**Comment by yi-Xu-0100** [comment]
可能网络问题，会去查询下最新版本，倒是不知道这个能不能在后台异步处理。

**Comment by kanjianjiuhao** [comment]
> 可能网络问题，会去查询下最新版本，倒是不知道这个能不能在后台异步处理。

另外带来个问题，V2EX的脚本最近都不能“自动”运行，重新登陆后也没解决，v1.0.8这个脚本版本。之前使用Chrome Web Store里最早的魂签扩展，没有类似问题

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 我使用一直没有问题，出现了什么返回？（v2.4.2）

**Comment by kanjianjiuhao** [comment]
> @kanjianjiuhao 我使用一直没有问题，出现了什么返回？（v2.4.2）

返回是正确的“已领取”，但设置每天00：30签到，直到早上也没能完成V2EX的签到，都还是需要手动（这样应该已经避过了论坛24小时签到机制）。另外一个V2EX的版本也尝试过，仍然是同样问题，两个脚本代码一样

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 

![image](https://user-images.githubusercontent.com/25523606/100425237-ca911e80-30c9-11eb-9dc9-1b4c5d61a795.png)

注意修改开始时间

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 而且这需要你的浏览器一直后台运行，电脑不断网

**Comment by kanjianjiuhao** [comment]
> 而且这需要你的浏览器一直后台运行，电脑不断网

我把签到开始时间设定在1800秒了，平时只锁屏不关电脑，到早上其他的签到正常，就V2EX的需要手动完成。
另外请问一个运行的机制，记得之前旧版本（没有修改运行时间），只要浏览器打开就会自动检查任务运行，中间关机错过时间也会重复运行的样子。新版本V2.4.2检查机制不一样了吗？运行时间关机会影响当天的所有签到？

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 如果你使用的是之前 v1版本的话，我不太清楚，现在都是 v2版本，这个只是浏览器插件，理论上说，只有浏览器打开后才会启动插件，插件才会轮询检查并签到。如果关闭浏览器，个人认为是不会后台运行，也就没有签到的可能。错过时间，重新打开时间会重新签到。应该有比较上次的签到时间

**Comment by kanjianjiuhao** [comment]
> @kanjianjiuhao 如果你使用的是之前 v1版本的话，我不太清楚，现在都是 v2版本，这个只是浏览器插件，理论上说，只有浏览器打开后才会启动插件，插件才会轮询检查并签到。如果关闭浏览器，个人认为是不会后台运行，也就没有签到的可能。错过时间，重新打开时间会重新签到。应该有比较上次的签到时间

明白这个机制，就是说即使错过了签到时间，只要再打开浏览器，仍然会检查执行情况并且会补充签到。今天我再尝试，仍然发现V2EX没有被签到，也还是手动完成的，不知道问题出在哪里。魂签2.4.2/V2EX脚本1.0.8。
请问是否有什么方法可以排查问题？

**Comment by yi-Xu-0100** [comment]
v2ex 的哪个版本，给链接看看

**Comment by kanjianjiuhao** [comment]
> v2ex 的哪个版本，给链接看看，有没有相关日志

魂签2.4.2
V2EX日志：
`{
"domain":
"www.v2ex.com",

"errno":
false,

"message":
"成功",

"url":
"https://www.v2ex.com"

}`
但今天也还是自己手动签到成功的，页面没有自动签到

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 脚本链接, 
![image](https://user-images.githubusercontent.com/25523606/100609211-95463400-3348-11eb-95a9-07ed4fa64acb.png)

看你的信息是成功的，但是没有签到吗？

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 我的和你的版本一样的，从代码上看，返回成功的话，应该是签到成功的。
```js
 if (/每日登录奖励/.test(ret.data)) return '成功';
```
其他的没有返回这个的

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/100609543-23221f00-3349-11eb-8013-4e567f465ee7.png)

能看到最近执行时间吗？

**Comment by kanjianjiuhao** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/100609543-23221f00-3349-11eb-8013-4e567f465ee7.png)
> 
> 能看到最近执行时间吗？

![2020-11-30_201736](https://user-images.githubusercontent.com/24827353/100609904-c3784380-3349-11eb-9b35-ad3c4d1b1213.png)
![Snipaste_2020-11-30_20-19-13](https://user-images.githubusercontent.com/24827353/100609918-c8d58e00-3349-11eb-8750-c44a37ace4f8.png)
我这里都是返回正常的，但实际V2EX并没有签到，所以很奇怪。其他的都正常，换成2.4.2的魂签后单V2EX不对
也老跑到YIXU兄你那边去，还想等着那边再更新版本，不知道是不是就我这问题严重（我是正常访问V2EX的，之前用CHORME STORE的魂签版本没问题）……

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 
![image](https://user-images.githubusercontent.com/25523606/100610296-6630c200-334a-11eb-945b-5e06334f711f.png)
直接点击 运行看看，是否会显示重复签到。明天多次运行脚本，看看结果是否都是 成功 。

**Comment by kanjianjiuhao** [comment]
> @kanjianjiuhao
> ![image](https://user-images.githubusercontent.com/25523606/100610296-6630c200-334a-11eb-945b-5e06334f711f.png)
> 直接点击 运行看看，是否会显示 已领取 。明天多次运行脚本，看看结果是否都是 成功 。

![Snipaste_2020-11-30_20-27-57](https://user-images.githubusercontent.com/24827353/100610444-b3149880-334a-11eb-940e-af72aa20a7af.png)

这几天都是手动按的，上面是我V2EX的打卡记录
现在直接点运行显示的是“执行成功"。
我明天再试试手动执行的情况，然后再来反馈，多谢yi-Xu-0100兄

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 

![image](https://user-images.githubusercontent.com/25523606/100610703-2b7b5980-334b-11eb-82a3-d284760efd27.png)

明天看看多次执行效果如何。 我印象中 v2ex 的签到时间验证有点怪怪的的。你可以看下19小时前，v2ex 的金币记录中是否有相关的签到记录。 
![image](https://user-images.githubusercontent.com/25523606/100610906-78f7c680-334b-11eb-9970-651747cc7b7d.png)

而且，我怀疑他是按照 8.00 更新签到时间表的，如果是这样，你设置为 0 点，soulsign 签到时确认为签到过的话，会默认不再检查是否签到，只会检查是否在线，等到 v2ex 8.00 更新签到表，soulsign 则默认今天是签到的。

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 建议明早，截图最近签到时间，确认是否在 0 点执行，然后在插件页面执行，截图结果，多次执行脚本，截图对应结果。方便复查可能的脚本结果。

**Comment by kanjianjiuhao** [comment]
> @kanjianjiuhao 建议明早，截图最近签到时间，确认是否在 0 点执行，然后在插件页面执行，截图结果，多次执行脚本，截图对应结果。方便复查可能的脚本结果。

好的，再次感谢提醒，也发现V2EX是要8点后才更新签到表。
明天凌晨我再看是否会自动执行签到，然后再手动执行。如果还是不行，我把魂签的运行时间改到8点之后再尝试。
印象是我改过魂签执行到凌晨才发现这个问题，想应该是与V2EX的更新签到表机制有冲突（但我在凌晨手动签到却是可以的，网页签到页面会提示已登陆签到）

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 可能是最近的变动，造成你认错了相应的签到顺序问题。今天你已经签到过了，明天应该脚本会显示 ”已领取“，但是 v2ex 页面显示未签到。（这是对的，已经凌晨验证今天的签到，签到过了，只能显示已领取。8.00 刷新，但不会去验证了）

如果是上述情况（脚本显示 ”已领取“+网页仍然可以签到），则你可以选择不签到，等脚本明天凌晨给你签到，但是每次白天逛 v2 的时候还是会发现可以签到。或者自己签到，但是脚本就只能验证到已领取了。

**Comment by kanjianjiuhao** [comment]
@yi-Xu-0100 测试后发现还是需要把魂签运行时间改到之前默认的8点之后，之前使用凌晨的运行时间，会与V2EX的签到机制不兼容。现在改到8点后，已经能自动完成签到。
有个情况，就是之前签到不成功，V2EX仍然反馈回执行成功，脚本也增加了成功计数，可能是这个造成了不会再检查漏签

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 是显示 ”已领取“ 还是 ”成功“？ 这两者都会认为是执行成功的而不再检查是否需要再签到。

**Comment by kanjianjiuhao** [comment]
> 这两者都会认为是执行成功的而不再检查是否需要再签到。

在魂签执行结果那显示的是“成功”。这次多亏了yi-Xu-0100兄提醒，把扩展的时候改到8点后就都正常可用了。

**Comment by yi-Xu-0100** [comment]
@kanjianjiuhao 只能说 v2ex 的判定确实有点问题
