### ISSUE TITLE
火狐设置为“当前标签打开链接”后，无法正常使用

### ISSUE THREAD

**Issue by hetting123** [inu1255/soulsign-chrome#179]
Firefox ，83或84正式版。

about:config，browser.link.open_newwindow,设置为1后，打开扩展的"任务管理",小窗口抖动，无法点击。

把browser.link.open_newwindow.override.external和browser.link.open_newwindow.restriction设置成-1.0.1.2.3，也没啥用😭

通过soulsign.inu1255.cn添加脚本进入管理页面，只提示添加成功，所有脚本都不显示。
恢复browser.link.open_newwindow默认值3，可以正常点击扩展图标进入管理页面，但脚本依然不显示，只能重装。

**Comment by inu1255** [comment]
太过久远、如有问题、请重提issue
