### ISSUE TITLE
能否考虑添加虾米音乐签到脚本

### ISSUE THREAD

**Issue by JO2EY** [inu1255/soulsign-chrome#18]
能否考虑添加虾米音乐签到脚本

**Comment by inu1255** [comment]
虾米音乐脚本已添加，不过需要将插件升级到1.1.0版本；
1.1.0版本支持引入外部js和cookie获取；因为虾米音乐的签到做了md5签名
目前1.1.0版本正在审核中，请等待审核通过自动升级或自己通过源代码安装

**Comment by JO2EY** [comment]
hello 感谢添加 不过虾米的脚本貌似有 bug ，一直提醒不在线

**Comment by inu1255** [comment]
@JO2EY 虾米音乐过段时间会需要滑块验证，滑块验证我没找到破解方案；
暂时只能调低脚本检查频率，避免经常骚扰
