### ISSUE TITLE
作者有考虑过为 Firefox 同步最新版本吗？

### ISSUE THREAD

**Issue by kkzhh** [inu1255/soulsign-chrome#181]
作者有考虑过为 Firefox 同步最新版本吗？不同步更新的原因是因为兼容性问题还是审核问题呢？

最近想做的一个网站签到，但因为网站的 cookie 存放位置很奇怪，触及了我的知识盲区，这导致即使登陆了，扩展里axios.post网站也显示未登陆，所以想要搞一个模拟点击的方法，比较简单，但主力是 Firefox，一直没更新这个功能，导致实现不了，很尴尬。

**Comment by inu1255** [comment]
@kkzhh  由于chrome审核不过，所以没有更新版本了，现在建议在仓库下载安装或者自己编译安装。
firefox其实是可以更新的，但是偷懒了没更新，我抽空去更新一下。

**Comment by kkzhh** [comment]
非常感谢作者，扩展非常棒，期待 Firefox 的新版本
