### ISSUE TITLE
脚本自动清空

### ISSUE THREAD

**Issue by Josoen** [inu1255/soulsign-chrome#182]
运行了两天的脚本今天突然不见了，包括设置那里默认设置数据也变成空白

**Comment by Josoen** [comment]
找到另一个问题，可能是原因，就是添加脚本后无法保存，报错undefined

**Comment by yi-Xu-0100** [comment]
@Josoen 尝试重置插件数据，注意插件数据备份，报错建议截图

**Comment by Josoen** [comment]
> @Josoen 尝试重置插件数据，注意插件数据备份，报错建议截图

感谢回复，重新安装插件之后问题暂时解决，觉得问题可能是插件加载时间很长，关掉Chrome来回几次才可以刷新出来

**Comment by ShadowEmbrace** [comment]
> 
> 
> > @Josoen 尝试重置插件数据，注意插件数据备份，报错建议截图
> 
> 感谢回复，重新安装插件之后问题暂时解决，觉得问题可能是插件加载时间很长，关掉Chrome来回几次才可以刷新出来

我是在火狐关闭插件再开就有了

**Comment by whyjxz14** [comment]
清空应该是。chrome zip加载的原因？是临时文件

**Comment by inu1255** [comment]
太过久远、如有问题、请重提issue
