### ISSUE TITLE
希望插件能增加自定义时间的循环签到，就可以开发更多玩法

### ISSUE THREAD

**Issue by lujc** [inu1255/soulsign-chrome#184]
我写了个苏宁牛转钱坤活动的自动收福气的脚本，很简单实用，可以用签到功能一键自动收福气值，福气值大约每1小时左右会满，需要设定周期循环收取，如果插件能增加时间循环签到，就能为很多类似的活动实现自动收取功能

**Comment by whyjxz14** [comment]
这个需求还是比较常见的，像天使动漫的打工也是6小时可以做一次，并不是所有的签到都是每天。不过可能感觉做成权限比较好。大部分脚本是不需要的。
然后如果不小心把数值设置的太小会不安全也影响性能。希望能检测到数值太小的话提示确认。

**Comment by inu1255** [comment]
新版本支持 `@freq` 设置运行频率
