### ISSUE TITLE
插件不运行，点击没有反应

### ISSUE THREAD

**Issue by erudite72** [inu1255/soulsign-chrome#185]
浏览器版本：Microsoft Edge版本 89.0.723.0 (官方内部版本) dev (64 位)
打开浏览器插件不运行，点击无反应，卸载重装就好了，出现频率不固定

**Comment by erudite72** [comment]
补充错误
![image](https://user-images.githubusercontent.com/38214509/107117165-491cf000-68b3-11eb-93d7-160478e5cf3c.png)

**Comment by yi-Xu-0100** [comment]
https://github.com/inu1255/soulsign-chrome/issues/222#issuecomment-932854533
