### ISSUE TITLE
如何禁止插件发送通知

### ISSUE THREAD

**Issue by gaowanliang** [inu1255/soulsign-chrome#192]
我不关心插件中的脚本是否正常升级，也不关心是不是签到成功或者是不在线，但是这个插件非要弄一个通知，而且无法关闭。所以如何禁止插件发送通知，或者可以关闭通知

**Comment by yi-Xu-0100** [comment]
@gaowanliang 
![image](https://user-images.githubusercontent.com/25523606/111890625-19224a00-8a26-11eb-9dd9-144daa3be74c.png)

我想这里可以设置，但是我不确定设置为多少是禁止通知。

**Comment by gaowanliang** [comment]
我觉得每天首次打开浏览器打开时都应该有个检测脚本更新的提示，就像初始化一样，单纯设置这一个应该没用，每次要去清通知很麻烦

**Comment by yi-Xu-0100** [comment]
@gaowanliang 我想你可以试着自己打包一个去除通知权限的版本，或者直接修改解压包中的 `manifest.json` 中的 `permissions`, 将 `notifications` 去除试试。

**Comment by inu1255** [comment]
最新版本增加了通知开关，点击插件图标可以设置
