### ISSUE TITLE
请问有部分脚本安装提示“缺少函数exports.run”

### ISSUE THREAD

**Issue by GD2021** [inu1255/soulsign-chrome#194]
例如：
1、v2ex签到

**Comment by yi-Xu-0100** [comment]
@GD2021 给出链接，可能你用的那个不能用了，换其他的试试

**Comment by GD2021** [comment]
> @GD2021 给出链接，可能你用的那个不能用了，换其他的试试

https://soulsign.inu1255.cn/scripts/378

**Comment by GD2021** [comment]
大大，还有“几鸡”这个脚本，安装上提示“domain配置不正确”，麻烦您看看
脚本链接：https://soulsign.inu1255.cn/scripts/394

**Comment by GD2021** [comment]
“鱼C论坛by yi-Xu-0100”也提示缺少函数exports.run。

链接：https://soulsign.inu1255.cn/script/yi-Xu-0100/%E9%B1%BCC%E8%AE%BA%E5%9D%9B.js#soulsign-install

**Comment by GD2021** [comment]
“智能电视网”执行结果显示 执行失败

链接：https://soulsign.inu1255.cn/script/lujc/%E6%99%BA%E8%83%BD%E7%94%B5%E8%A7%86%E7%BD%91.js#soulsign-install

**Comment by yi-Xu-0100** [comment]
@GD2021 你安装的插件版本是？
