### ISSUE TITLE
脚本的 param 在哪里传进去？

### ISSUE THREAD

**Issue by morefreeze** [inu1255/soulsign-chrome#2]
> 支持用户填写参数，用于用户填写账号密码进行自动登录的场景。使用方法参考 public/demos/m.jd.js

看了m.jd.js的脚本，没看明白这个param.name / param.pwd 在哪里传？

**Comment by inu1255** [comment]
@morefreeze 需要版本1.0.4+的版本，目前还未通过应用商店的审核，只能通过build.crx或者自己编译来体验这个功能，我在README中添加了图片介绍

**Comment by morefreeze** [comment]
cool!
