### ISSUE TITLE
有没大神能制作这两个音乐下载网站的脚本或者提供下教程非常感谢

### ISSUE THREAD

**Issue by yejinson** [inu1255/soulsign-chrome#212]
https://www.hifini.com/
https://dsdlove.com/

**Comment by langzigyq** [comment]
hifini就是garbage，站长也是个scumbag。绝对不会给这种网站做签到的。

推荐用MusicTools ，https://tool.yijingying.com/musictools/    完全免费，可切换音源，各种品质随意下载

**Comment by langzigyq** [comment]
hifini就是garbage，站长也是个scumbag。绝对不会给这种网站做签到的。

推荐用MusicTools ，https://tool.yijingying.com/musictools/ 完全免费，可切换音源，各种品质随意下载

**Comment by langzigyq** [comment]
第二个网站的签到脚本已上传到魂签。
Trix360音乐  https://soulsign.inu1255.cn/scripts/500

**Comment by yejinson** [comment]
> hifini就是garbage，站长也是个scumbag。绝对不会给这种网站做签到的。
> 
> 推荐用MusicTools ，https://tool.yijingying.com/musictools/ 完全免费，可切换音源，各种品质随意下载

那个站长怎么啦，有时候搜歌经常搜到那个网站。下载软件我有，因为有时候一些稀缺资源软件里没有或者下过来的是假无损就想下过来对比下看看万一有不一样的版本。

**Comment by yejinson** [comment]
> 第二个网站的签到脚本已上传到魂签。 Trix360音乐 https://soulsign.inu1255.cn/scripts/500

用上了，谢谢大神。

**Comment by yejinson** [comment]
> 第二个网站的签到脚本已上传到魂签。 Trix360音乐 https://soulsign.inu1255.cn/scripts/500

大神能麻烦你再帮忙做两个音乐站点吗 辛苦了
https://www.maomicd.com/
https://www.wlyxmusic.net/

**Comment by inu1255** [comment]
https://github.com/inu1255/soulsign-chrome/issues/309
