### ISSUE TITLE
内容安全策略问题

### ISSUE THREAD

**Issue by gaowanliang** [inu1255/soulsign-chrome#215]
报错信息：
```
Refused to load the script 'http://soulsignchrome.inu1255.cn/js/manifest.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
![image](https://user-images.githubusercontent.com/41822468/128799430-4af70b4f-3ae8-4f50-a044-ed1177ffc5b2.png)

使用浏览器：Microsoft Edge 版本 92.0.902.67 (官方内部版本) (64 位)

导致直接后果：前一段时间只是popup打不开，显示为空白，现在连整个插件界面也显示为空白了，应该是内容安全策略更新了
![image](https://user-images.githubusercontent.com/41822468/128799650-d2c6d43e-20b4-4fc6-acdf-14876f98fe93.png)

**Comment by yi-Xu-0100** [comment]
https://github.com/inu1255/soulsign-chrome/issues/222#issuecomment-932854533

**Comment by inu1255** [comment]
2.5.1 已修复
