### ISSUE TITLE
签到失败   yi-Xu-0100

### ISSUE THREAD

**Issue by 253253a** [inu1255/soulsign-chrome#217]
大大 你写的聚创网站签到 1.07版本提示 **需要登录** 我在网站从新再次登录还是不是  ，谢谢帮忙解决下

**Comment by yi-Xu-0100** [comment]
@253253a 很高兴我的脚本可能有所帮助，如果还是脚本有问题，建议关闭这个 issue ，然后去 https://github.com/yi-Xu-0100/soulsign-scripts/issues 提交 issue。
当然，这个网站我没法注册，同样需要你提供账号密码给我测试使用。发我邮箱 yi_Xu#yixuju.cn  #换@
