### ISSUE TITLE
插件经常失效

### ISSUE THREAD

**Issue by erudite72** [inu1255/soulsign-chrome#219]
在edge浏览器dev版本中，经常失效需要重新安装
Refused to load the script 'http://soulsignchrome.inu1255.cn/sw-install.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by yi-Xu-0100** [comment]
https://github.com/inu1255/soulsign-chrome/issues/222#issuecomment-932854533

**Comment by inu1255** [comment]
2.5.1 已修复
