### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by hodxnvv** [inu1255/soulsign-chrome#222]
第一次安装运行正常，
Chrome 已是最新版本
版本 94.0.4606.54（正式版本） （64 位）
win10系统

Refused to load the script 'http://soulsignchrome.inu1255.cn/sw-install.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by xingxing404** [comment]
我也遇上了同样的问题，应该是chrome最近几个版本更新才出现的（ 94.0.4606.61）

**Comment by bluceli0** [comment]
更新Chrome版本后就不能用了

**Comment by 253253a** [comment]
版本 94.0.4606.54（正式版本） （32 位） 昨天都是好的 ，今天就不行了
Refused to load the script 'http://soulsignchrome.inu1255.cn/sw-install.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by SekiBetu** [comment]
me too

**Comment by SekiBetu** [comment]
应该是安全性的改动，要使用白名单告诉客户端允许加载和不允许加载的内容。
https://content-security-policy.com/
https://developers.google.com/web/fundamentals/security/csp?hl=zh-cn

**Comment by lyc8503** [comment]
+1 同样在更新 Chrome 后无法使用

**Comment by lichang1019** [comment]
edge也不能用了 ，也是这个错误

**Comment by xjbzcvbnm** [comment]
不知道 还会不会更新..

**Comment by yi-Xu-0100** [comment]
不知道，使用非自动更新版是否有问题？

**Comment by freemedom** [comment]
兄弟们，降级可以用
但是降级卸载的时候要备份一下数据啊。。。

**Comment by SekiBetu** [comment]
> 兄弟们，降级可以用 但是降级卸载的时候要备份一下数据啊。。。

一辈子用老版本Chrome嘛

**Comment by freemedom** [comment]
> > 兄弟们，降级可以用 但是降级卸载的时候要备份一下数据啊。。。
> 
> 一辈子用老版本Chrome嘛

等作者修复吧，我昨天试了一下修复，结果修不了。。。

**Comment by yi-Xu-0100** [comment]
https://github.com/yi-Xu-0100/soulsign-scripts/blob/main/build2.4.3.zip

可以尝试用我打包的这个，其实就是本项目，用 `npm build` 打包的，这样打包的是非自动更新的。与发布的自动更新版本不同，个人使用无误，打包的版本有问题可以在这里回复。怕我打包的有问题的，可以自行 clone 当前仓库，`npm install` 之后再 `npm build` 即可。

**Comment by SekiBetu** [comment]
> [https://github.com/yi-Xu-0100/soulsign-scripts/blob/main/build2.4.3.zip](https://github.com/yi-Xu-0100/soulsign-scripts/blob/main/build2.4.3.zip?rgh-link-date=2021-10-03T03%3A13%3A32Z)
> 
> 可以尝试用我打包的这个，其实就是本项目，用 `npm build` 打包的，这样打包的是非自动更新的。与发布的自动更新版本不同，个人使用无误，打包的版本有问题可以在这里回复。怕我打包的有问题的，可以自行 clone 当前仓库，`npm install` 之后再 `npm build` 即可。

代码层级的错误，不能通过再打包解决的，你这个我试了，依然报错

**Comment by freemedom** [comment]
@SekiBetu  我这里可以用

**Comment by yi-Xu-0100** [comment]
@SekiBetu 你是否尝试的是我编译的版本？这里的自动更新，是指作者为插件避开 goolge store 而制作的第三方加载并更新本地脚本内容。当然这样会引入后台文件并带来可能的安全问题。

但是这样会导致无法本地调试（会被自动更新到指定的版本），见 https://github.com/inu1255/soulsign-chrome/issues/121 ，作者也将自动更新版本（ `npm run build-update`）和非自动更新版本（`npm run build`）分别给出。其中 `sw-install.js` 主要是自动更新部分带来的。

最后，可能还是有问题的，可以检查下这个 issue 所提到的问题。https://github.com/inu1255/soulsign-chrome/issues/128

**Comment by SekiBetu** [comment]
> @SekiBetu 你是否尝试的是我编译的版本？这里的自动更新，是指作者为插件避开 goolge store 而制作的第三方加载并更新本地脚本内容。当然这样会引入后台文件并带来可能的安全问题。
> 
> 但是这样会导致无法本地调试（会被自动更新到指定的版本），见 #121 ，作者也将自动更新版本（ `npm run build-update`）和非自动更新版本（`npm run build`）分别给出。其中 `sw-install.js` 主要是自动更新部分带来的。
> 
> 最后，可能还是有问题的，可以检查下这个 issue 所提到的问题。#128

卸载插件后再装生效了，不能覆盖式刷新插件，估计有残留

**Comment by lyc8503** [comment]
> @SekiBetu 你是否尝试的是我编译的版本？这里的自动更新，是指作者为插件避开 goolge store 而制作的第三方加载并更新本地脚本内容。当然这样会引入后台文件并带来可能的安全问题。
> 
> 但是这样会导致无法本地调试（会被自动更新到指定的版本），见 #121 ，作者也将自动更新版本（ `npm run build-update`）和非自动更新版本（`npm run build`）分别给出。其中 `sw-install.js` 主要是自动更新部分带来的。
> 
> 最后，可能还是有问题的，可以检查下这个 issue 所提到的问题。#128

这个版本可以正常运行, 但无法覆盖安装之前的版本. 之前版本的脚本如何提取出来呢?

**Comment by yi-Xu-0100** [comment]
@lichang1019 覆盖安装有问题，参考 #128 ，然后导出脚本试试。再重装防止有问题。

**Comment by SekiBetu** [comment]
既然解决了，考虑给普通用户一个release吗，虽然可以自己build
