### ISSUE TITLE
插件有bug啊，刚开始安装能点出菜单，过一段时间就不行了，必须卸载插件重新安装，chrome最新版

### ISSUE THREAD

**Issue by yejinson** [inu1255/soulsign-chrome#226]
![2](https://user-images.githubusercontent.com/73937339/137495266-6c09bb70-f457-4180-9fa0-71078b32d287.png)
![1](https://user-images.githubusercontent.com/73937339/137495271-21f0edda-7935-4614-9473-75552bc59af2.png)
如图 单击图标不显示菜单 只有一个没有内容的小方框

**Comment by byesohu** [comment]
问题一样，好久不能用了。

**Comment by zhouzikk** [comment]
还没处理。

**Comment by zxsn** [comment]
同样问题，edge

**Comment by zxsn** [comment]
https://github.com/inu1255/soulsign-chrome/issues/222#issuecomment-932865616
使用这个打包的插件可以解决此问题。

**Comment by zxsn** [comment]
> 还没处理。

看楼下

**Comment by yejinson** [comment]
> [#222 (comment)](https://github.com/inu1255/soulsign-chrome/issues/222#issuecomment-932865616) 使用这个打包的插件可以解决此问题。

谢谢这个可以用，但发现贴吧和吾爱会失效，不知道是扩展问题还是脚本问题。

**Comment by asunshy** [comment]
同问，一样的问题。

**Comment by cacacai** [comment]
同样问题+1 ，刚安装之后可以使用，一段时间之后就无法使用了，使用的是Release v2.4.3 版本
![image](https://user-images.githubusercontent.com/18202887/149877890-b77524ca-3b2e-43d2-9c7b-2d24cf1578ef.png)
> Refused to load the script 'http://soulsignchrome.inu1255.cn/sw-install.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

chrome 版本 版本 97.0.4692.71（正式版本） （64 位）

**Comment by FairyWorld** [comment]
我也遇到了这个问题

**Comment by inu1255** [comment]
可以试试 2.5.2 版本还有问题没
