### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by zszczh** [inu1255/soulsign-chrome#228]
Refused to load the script 'http://soulsignchrome.inu1255.cn/sw-install.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

上下文
pages/popup.html

堆叠追踪
pages/popup.html:0 (匿名函数)

**Comment by yi-Xu-0100** [comment]
https://github.com/inu1255/soulsign-chrome/issues/222#issuecomment-932854533

**Comment by zszczh** [comment]
> [#222 (comment)](https://github.com/inu1255/soulsign-chrome/issues/222#issuecomment-932854533)

谢谢，这个问题解决了。但又出现另外一个问题，如图。我在google chrome浏览器上在脚本推荐里选择任何脚本安装都出现这个页面，就出现在点击“安装”后。换Firefox，脚本可以顺利安装。
![捕获](https://user-images.githubusercontent.com/30950457/137831945-58e81afe-7e6f-4795-b7ff-30bb549dd8ee.PNG)

**Comment by zszczh** [comment]
> [#222 (comment)](https://github.com/inu1255/soulsign-chrome/issues/222#issuecomment-932854533)

谢谢，问题解决了。
