### ISSUE TITLE
有没大神能出个脚本制作教程啊

### ISSUE THREAD

**Issue by yejinson** [inu1255/soulsign-chrome#235]
自己不会做，老是麻烦大神帮忙做大神也没空，唉，要是有教程就好了。

**Comment by yejinson** [comment]
如果有容易上手的教程，让更多人参与进来，脚本也会多很多，现在有点少。

**Comment by freemedom** [comment]
let run = async function (param) {
  if (!(await check(param))) throw '需要登录';
  var resp = await axios.get('https://www.v2ex.com/mission/daily');
  if (/你要查看的页面需要先登录/.test(resp.data)) throw '需要登录';
  if (/每日登录奖励已领取/.test(resp.data)) return '重复签到';
  var once = /redeem\?once=(.*?)'/.exec(resp.data);
  if (!once) throw '未找到 once';
  var resp1 = await axios.get(`https://www.v2ex.com/mission/daily/redeem?once=${once[1]}`);
  if (/请重新点击一次以领取每日登录奖励/.test(resp1.data)) throw '请重新签到';
  else if (/每日登录奖励已领取/.test(resp1.data)) {
    let resp = await axios.get('https://www.v2ex.com/balance');
    let today = new Date(Date.now()).toISOString().replace(/[^0-9]/g, '');
    let reward = RegExp(`${today.slice(0, 8)} 的每日登录奖励 (\\d+) 铜币`, 'g').exec(resp.data);
    if (reward) return `签到奖励: ${reward[1]} 铜币`;
    else return '成功签到';
  } else throw '无法确认签到结果';
};

let check = async function (param) {
  var resp = await axios.get('https://www.v2ex.com/t/718092');
  return !/现在注册/.test(resp.data);
};

module.exports = { run, check };

**Comment by freemedom** [comment]
原理大概就是，run是每天执行一次，check是检查今天是否执行了（还有就是保持cookie不过期）
你要写的话得有编程基础，查一些JavaScript的语法，还要有点网络请求的概念

**Comment by yejinson** [comment]
> 原理大概就是，run是每天执行一次，check是检查今天是否执行了（还有就是保持cookie不过期） 你要写的话得有编程基础，查一些JavaScript的语法，还要有点网络请求的概念

谢谢大神，0基础该从哪开始学呢

**Comment by freemedom** [comment]
0基础到能写出来估计得学10几个小时

**Comment by freemedom** [comment]
从哪开始学，从js开始
