### ISSUE TITLE
求增加单个脚本签到间隔时间设置

### ISSUE THREAD

**Issue by yejinson** [inu1255/soulsign-chrome#236]
如题，有的网站不能每天签到，是两天签到一次。

**Comment by yi-Xu-0100** [comment]
感觉不太常见，临时解决方案的话，可以给脚本做判断。

**Comment by yejinson** [comment]
> 感觉不太常见，临时解决方案的话，可以给脚本做判断。

https://www.wlyxmusic.net/  这个，小白只会录不知道咋改。虽然不常见，但是只要有一个就会影响使用，因为失败的时候会一直重试，我只能全局改重试时间，这样其他需要每天签到的有断签风险，而且扩展图标上会隔天出现因为签到失败的数字脚标。

**Comment by yi-Xu-0100** [comment]
我注册了一下，大致了解了，需要一段时间写。验证2天一次，没法操作了，不想多注册。如果有账号密码，还没有签到，信任我的话，可以发我邮箱（yi_Xu#yixuju.cn #换成@），我来尝试写个脚本。

或者给出你的签到脚本，我看下能否加个判断。

**Comment by yejinson** [comment]
> 

发你邮箱了，辛苦了谢谢。

**Comment by yejinson** [comment]
> 我注册了一下，大致了解了，需要一段时间写。验证2天一次，没法操作了，不想多注册。如果有账号密码，还没有签到，信任我的话，可以发我邮箱（yi_Xu#[yixuju.cn](https://yixuju.cn) #换成@），我来尝试写个脚本。
> 
> 或者给出你的签到脚本，我看下能否加个判断。

我的账号要0点后才能申请签到，发你邮箱了，辛苦了谢谢。

**Comment by yi-Xu-0100** [comment]
@yejinson 已收到，邮件已回复！

**Comment by yejinson** [comment]
> @yejinson 已收到，邮件已回复！

谢谢大神，回你邮件了。

**Comment by inu1255** [comment]
最新版本, 支持在脚本中使用 @freq 设置签到频率
