### ISSUE TITLE
有bug莫名其妙会停止签到没有任何错误提示

### ISSUE THREAD

**Issue by yejinson** [inu1255/soulsign-chrome#239]
<a href="https://sm.ms/image/OVWvTRsHmjSCZYo" target="_blank"><img src="https://s2.loli.net/2022/01/06/OVWvTRsHmjSCZYo.png" alt="quicker_72a7f100-12d3-450b-a0c6-0453df1f0179.png"></a>

**Comment by yejinson** [comment]
突然可以了，一脸懵逼。

**Comment by yejinson** [comment]
<img src='https://s2.loli.net/2022/02/19/voea6Zjf8WV7N9I.png' title='quicker_bd56934b-d778-43cc-af79-58893acae494.png' />
又莫名其妙停止签到了，也没异常提示，真是醉了。

**Comment by yi-Xu-0100** [comment]
不会这几天没打开浏览器吧

**Comment by yejinson** [comment]
> 不会这几天没打开浏览器吧

当然不是啊浏览器每天都开，应该是修改版的bug，用回原版和商店版正常，但是原版重启就挂了，商店版好多脚本都用不了。没一个能用的，唉，希望能尽快修复。

**Comment by yi-Xu-0100** [comment]
不开浏览器怎么签到呢，这个就是依托浏览器签到，不是云签到。

**Comment by yejinson** [comment]
> 不开浏览器怎么签到呢，这个就是依托浏览器签到，不是云签到。

我少打了个逗号，我的意思是浏览器每天都开。

**Comment by yejinson** [comment]
> 不开浏览器怎么签到呢，这个就是依托浏览器签到，不是云签到。

现在又停了，看了下大概一个月左右就会自动罢工，修复下bug吧辛苦了。

**Comment by yi-Xu-0100** [comment]
@yejinson 我这边没法复现，也不知道什么引起的。。。

**Comment by yejinson** [comment]
> @yejinson 我这边没法复现，也不知道什么引起的。。。

发完贴之后又好了有点玄学，我再观察观察吧，不好意思。
