### ISSUE TITLE
怎么自己写一个jio本

### ISSUE THREAD

**Issue by fortunelee** [inu1255/soulsign-chrome#24]
怎么自己写一个jio本

**Comment by inu1255** [comment]
需要会javascript和抓包分析，然后参考public/demos就可以写出自己的脚本了

一般流程是
1. 登录网站
1. 开chrome调试 (当然最好用charles代理的方式，可以记录和重放请求)
1. 点击签到
1. 分析签到请求
1. 写代码

**Comment by fortunelee** [comment]
我还要写登陆的代码吗，登陆后，点击签到，弹了一个窗口后再点击确定才是正式签到成功的操作

**Comment by fortunelee** [comment]
// ==UserScript==
// @name             考勤
// @namespace         https://github.com/inu1255/soulsign-chrome
// @version           1.0.0
// @author            test
// @loginURL          http://itsp.orientsec.com.cn/dfzq-sign/sign.do
// @updateURL         https://gitee.com/inu1255/soulsign-chrome/raw/master/public/demos/jd.js
// @expire            900e3
// @domain            itsp.orientsec.com.cn
// ==/UserScript==
const opt = {
    headers: {
        'origin': 'http://itsp.orientsec.com.cn',
        'X-Requested-With': 'XMLHttpRequest',
        'referer': 'http://itsp.orientsec.com.cn/dfzq-sign/sign.do?xcase=signIndex',
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    }
};
exports.run = async function() {
    var { data } = await axios.post('http://itsp.orientsec.com.cn/dfzq-sign/sign.do?xcase=doSign','optionCode=1&signTime=08:42:13&signDesc=',opt);
    if (true) return '签到成功';
    throw '失败';
};

exports.check = async function() {
    var { status } = await axios.get('http://itsp.orientsec.com.cn/dfzq-sign/sign.do?xcase=signIndex', { timeout: 10e3, maxRedirects: 0 });
    return status == 200;
};

**Comment by inu1255** [comment]
一般不用，登录让用户自己手动登录；当然你也可以把登录逻辑写在check中；
如果包含登录，自己用的脚本可以把账号密码写死，如果拿给其它人用可以通过 param指定，可以参考demos/tsdm.love.js, demos/m.jd.js

**Comment by fortunelee** [comment]
我那个写的对吗？？？大佬

**Comment by inu1255** [comment]
@fortunelee 
你可以自己测试一下，我这边访问不了你脚本里边的网址

**Comment by fortunelee** [comment]
我用java写了一个签到的，要不要上传上去

**Comment by fortunelee** [comment]
@inu1255

**Comment by inu1255** [comment]
@fortunelee 
用java写的插件不支持，只支持javascript的脚本

**Comment by fortunelee** [comment]
@inu1255 老哥，那个插件google浏览器安装不了了
