### ISSUE TITLE
偶尔运行了不能正常运行的脚本后，脚本就显示不出来了

### ISSUE THREAD

**Issue by TomIsFat** [inu1255/soulsign-chrome#241]
![图片](https://user-images.githubusercontent.com/76768214/148882383-173a89d7-0620-4f4f-9ad5-0c632a7cf99c.png)
偶尔运行了不能正常运行的脚本后，脚本就显示不出来了
虽然重启浏览器可以解决，但是控制台的数据在关闭浏览器的时候就没了

--火狐浏览器v2.4.2

**Comment by yi-Xu-0100** [comment]
我也是用火狐的，可以右键点管理插件，点击开关2次，重启下插件，就不用关闭浏览器了。
