### ISSUE TITLE
扩展卡死无法打开？

### ISSUE THREAD

**Issue by 2640yang** [inu1255/soulsign-chrome#243]
![image](https://user-images.githubusercontent.com/85521868/153728717-a8e2b73d-99bd-4dac-af08-2877fc02dd05.png)
这个是扩展管理界面
![image](https://user-images.githubusercontent.com/85521868/153728746-59106b44-789c-40f6-b2b6-657fb4f3704b.png)

![image](https://user-images.githubusercontent.com/85521868/153728743-8175de11-889f-45b4-b111-ae396a001b39.png)

**Comment by TomIsFat** [comment]
我也有相同问题
Edge 102.0.1245.30 (正式版本) (64 位) 测试 魂签 2.4.3和2.4.2版本均有此问题
Firefox运行2.4.2正常

**Comment by inu1255** [comment]
2.5.1 已修复
