### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by SekiBetu** [inu1255/soulsign-chrome#251]
Manifest version 2 is deprecated, and support will be removed in 2023. 
See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by inu1255** [comment]
manifest version 3似乎不支持`chrome.webRequest`，大多数接口会校验 Referer、Origin 这些请求头的设置都依赖于`chrome.webRequest`。所以暂时不能迁移到v3
