### ISSUE TITLE
关于迁移到manifest v3

### ISSUE THREAD

**Issue by youkoulc** [inu1255/soulsign-chrome#266]
现在可以正常使用但会提示错误，但 chrome 2023年一月起就不再支持运行Manifest V2 扩展程序，作者有空迁移一下吧。
![image](https://user-images.githubusercontent.com/49615746/175919819-e097e393-8293-4608-8479-fe568f46f60e.png)

**Comment by inu1255** [comment]
manifest version 3似乎不支持`chrome.webRequest`，大多数接口会校验 Referer、Origin 这些请求头的设置都依赖于`chrome.webRequest`。所以暂时不能迁移到v3
