### ISSUE TITLE
我的chrome安装2.4.3版本或者2.4.2较新新版本，都会提示错误，点击插件图标没有菜单，只有个空白的小白框出现。右键也只是灰色的不可点的菜单

### ISSUE THREAD

**Issue by happyfanyiming** [inu1255/soulsign-chrome#278]
我的chrome安装2.4.3版本或者2.4.2较新新版本，都会提示错误，点击插件图标没有菜单，只有个空白的小白框出现。右键也只是灰色的不可点的菜单

**Comment by happyfanyiming** [comment]
Firefox 就正常，chrome 就安装不上新版 安装商店的版本就没问题。

**Comment by blizzards0ne** [comment]
所有git上的版本（2.2.0~2.4.3）都有这个问题，chrome商店的就正常，不知道什么原因。

**Comment by happyfanyiming** [comment]
哦，那有时间可以麻烦大佬更新下商店版本的魂签吗？ ：）

在 2022-10-11 09:00:43，"blizzards0ne" ***@***.***> 写道：

所有git上的版本（2.2.0~2.4.3）都有这个问题，chrome商店的就正常，不知道什么原因。

**Comment by 1ninty2** [comment]
有解决方案了吗，我也是这样

**Comment by hongjh2** [comment]
修改2.4.3插件文件夹里面的manifest.json文件，最后一段content_security_policy关键词改成这样，即可，参考最新的补丁提交改的
"content_security_policy":"script-src 'self' 'unsafe-eval'; object-src 'self'; script-src-elem 'self' 'unsafe-eval' http://soulsignchrome.inu1255.cn"}

**Comment by Cristimo** [comment]
> 

非常感谢给出了可行的解决方案 @

**Comment by inu1255** [comment]
感谢 @hongjh2 的解答  
由于工作和家庭原因，项目一直疏于维护，非常抱歉，现已发布了新版本

**Comment by YujiaCheng1996** [comment]
v2.5.4
按照这么修改依旧报错，nuxt里报的popup.html未找到，退回v2.4.3什么都不改反而没有问题。

**Comment by inu1255** [comment]
@YujiaCheng1996 这应该是因为2.4.3及之前的版本启用了service worker自动更新，可以参考图中操作注销调service worker。然后再到浏览器的扩展管理中重新加载一下试试。
![image](https://github.com/inu1255/soulsign-chrome/assets/5772409/6d099437-5b52-4a5b-89f2-3ff292165237)
![image](https://github.com/inu1255/soulsign-chrome/assets/5772409/0d15b08c-df71-48ec-841c-635825b1a134)
