### ISSUE TITLE
天翼云盘签到脚本从几天前开始签到失败

### ISSUE THREAD

**Issue by zszczh** [inu1255/soulsign-chrome#289]
显示的错误消息：
{ "message": "Request failed with status code 400", "name": "Error", "stack": "Error: Request failed with status code 400\n at createError (webpack-internal:///FtD3:16:15)\n at settle (webpack-internal:///21It:17:12)\n at XMLHttpRequest.handleLoad (webpack-internal:///7GwW:61:7)", "config": { "url": "https://m.cloud.189.cn/userSign.action", "method": "get", "headers": { "Accept": "application/json, text/plain, */*", "Host": "m.cloud.189.cn", "Accept-Encoding": "gzip, deflate", "_referer": "https://m.cloud.189.cn/zhuanti/2016/sign/index.jsp?albumBackupOpened=1" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 10000, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 } }

不知道是我的问题还是天翼云那边的问题

**Comment by yi-Xu-0100** [comment]
@zszczh 那个脚本？

**Comment by zszczh** [comment]
> @zszczh 那个脚本？

就是您的那个“cloud189签到”脚本

**Comment by yi-Xu-0100** [comment]
@zszczh 我用的没有问题，可以尝试自己去cloud189网盘登陆一下，有的时候自动登陆有问题

**Comment by zszczh** [comment]
> @zszczh 我用的没有问题，可以尝试自己去cloud189网盘登陆一下，有的时候自动登陆有问题

我这边可以自动登录，打开189的网址会在登录界面停个一两秒后跳转到网盘界面。也尝试过退出账号重新登录，还是不行。

**Comment by yi-Xu-0100** [comment]
@zszczh 

- https://github.com/yi-Xu-0100/soulsign-scripts/issues/52#issuecomment-1175747663

自己手动签到一次，然后关闭脚本，第二天再打开，试试

**Comment by zszczh** [comment]
@yi-Xu-0100 不好意思才看到。您说的手动签到是在app上签吗？网页上我一直没找到签到的地方。

**Comment by yi-Xu-0100** [comment]
@zszczh 是的，或者说，放弃一天的签到，等第二天，看下就好，不过要注意，先关闭这个签到脚本，第二天再打开。

**Comment by zszczh** [comment]
@yi-Xu-0100 好的，我这两天再试试。谢谢！

**Comment by zszczh** [comment]
@yi-Xu-0100 这几天我试了试，关闭脚本隔一天再打开的办法也不起作用

**Comment by inu1255** [comment]
@zszczh 可以试试 2.5.1 版本，修复了一些请求头设置失败的问题，有可能是这个问题导致的
