### ISSUE TITLE
安装报错求大佬更新

### ISSUE THREAD

**Issue by XiangLong6** [inu1255/soulsign-chrome#303]
2.4.3安装报错
![image](https://user-images.githubusercontent.com/108725882/218512510-652e563c-a27e-49e6-a7f1-61872db8e65e.png)
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
{"name":"魂签","version":"2.4.3","description":"自动签到","author":"inu1255","manifest_version":2,"icons":{"16":"icons/16.png","48":"icons/48.png","96":"icons/96.png","128":"icons/128.png"},"permissions":["<all_urls>","tabs","cookies","storage","notifications","webNavigation","webRequest","webRequestBlocking"],"browser_action":{"default_title":"魂签","default_icon":"icons/48.png","default_popup":"pages/popup.html"},"background":{"page":"pages/background.html"},"options_page":"pages/options.html","content_scripts":[{"js":["js/manifest.js","js/vendor.js","js/inject.js"],"run_at":"document_start","matches":["<all_urls>"],"all_frames":true}],"content_security_policy":"script-src 'self' 'unsafe-eval'; object-src 'self'"}

**Comment by inu1255** [comment]
manifest version 3似乎不支持`chrome.webRequest`，大多数接口会校验 Referer、Origin 这些请求头的设置都依赖于`chrome.webRequest`。  
所以暂时不能迁移到v3
