### ISSUE TITLE
管理页面被屏蔽

### ISSUE THREAD

**Issue by zszczh** [inu1255/soulsign-chrome#304]
最近两天扩展程序的管理页面打不开。重装了两次，每次都是刚装好时还正常，第二天再看就打不开页面了。
![2023-02-28_104750](https://user-images.githubusercontent.com/30950457/221741624-a856252a-afd2-4ecb-bbd4-1d93dbb4c586.png)
![2023-02-28_104712](https://user-images.githubusercontent.com/30950457/221741667-17d6fad9-fca5-46e3-b4cd-f7e4a3a3c2b9.png)

**Comment by cool-delete** [comment]
+1

**Comment by saglb** [comment]
有解决方法吗

**Comment by yi-Xu-0100** [comment]
firefox 的插件一直好使，可以试试。

**Comment by inu1255** [comment]
@zszczh @cool-delete @saglb 麻烦提供一下浏览器版本，这边没有复现

**Comment by inu1255** [comment]
可能是新版本设置页面变化导致的(之前是 /pages/options.html 现在是 /options.html)，可以试试新版

**Comment by zszczh** [comment]
> 可能是新版本设置页面变化导致的(之前是 /pages/options.html 现在是 /options.html)，可以试试新版

后来我换到firefox上用了。更新新版本后发现了个问题，我开个新issue说。

**Comment by inu1255** [comment]
firefox忘记更新了，现已更新到 2.5.4

**Comment by zszczh** [comment]
> firefox忘记更新了，现已更新到 2.5.4

更新后的这两天又遇到些问题：
1.从“脚本推荐”里安装脚本跳转回脚本列表页面后，脚本列表有很大概率不会显示，只有“暂无数据”的提示。刷新页面无用，只有关闭浏览器再重新打开后才恢复正常；
2.每次打开firefox浏览器，签到脚本都会按顺序重头执行一遍，不管今天是否已经执行过了。是“任务循环频率”设置的问题吗？我已经设置成86400秒了；
3.一些更新之前可以正常运行的脚本在更新后会执行失败。我观察到的现象是脚本打开签到页面后停留两三秒，然后就关闭了页面，没有执行后续的程序。

**Comment by inu1255** [comment]
第三点可以提供一下脚本吗？

**Comment by zszczh** [comment]
> 第三点可以提供一下脚本吗？

我整理了下出问题的脚本，分成了三大类
[有问题的脚本.txt](https://github.com/inu1255/soulsign-chrome/files/12447447/default.txt)

**Comment by inu1255** [comment]
一、执行不到最后一步就结束，显示签到失败
全部不能注册

二、没执行到最后一步，却显示签到成功
录制的脚本没有找到指定元素时不会报错导致的,后面优化一下
1. 偶尔会出现,我看代码中元素是有的,我明天再试试
2. openedv页面代码变化了,请重新录制试试

三、一直显示不在线，但实际上可以打开网页
1. 不能注册
2. 这边测试不设置账号密码，手动登录是可以的
3. 不能注册

**Comment by zszczh** [comment]
> 



> 一、执行不到最后一步就结束，显示签到失败 全部不能注册
> 
> 二、没执行到最后一步，却显示签到成功 录制的脚本没有找到指定元素时不会报错导致的,后面优化一下
> 
> 1. 偶尔会出现,我看代码中元素是有的,我明天再试试
> 2. openedv页面代码变化了,请重新录制试试
> 
> 三、一直显示不在线，但实际上可以打开网页
> 
> 1. 不能注册
> 2. 这边测试不设置账号密码，手动登录是可以的
> 3. 不能注册

没关系，注册不了的是pt站，都不好注册

**Comment by zszczh** [comment]
几天以来出现了些新问题：
1.不会自动签到 ，只有“人大经济论坛”脚本正常，而且每打开一次firefox就运行一次。其他的脚本显示的执行时间是几天之前，实际上我每天都手动挨个点击运行过。每次重新启动firefox后，脚本列表所显示的脚本状态都会回到几天之前，除了“人大经济论坛”。
![2023-09-01_085003](https://github.com/inu1255/soulsign-chrome/assets/30950457/a21831b6-9b8f-436c-84de-cd5f00aee96b)

2.当脚本运行时刷新脚本管理页面，脚本列表不会显示。解决办法和之前一样，关闭浏览器再打开，然后又导致“人大经济论坛”脚本重新运行一次。
![2023-09-01_090000](https://github.com/inu1255/soulsign-chrome/assets/30950457/e0892cf9-a185-403f-8f54-78c38eeafa3e)

**Comment by inu1255** [comment]
当前插件的版本是多少？

**Comment by zszczh** [comment]
> 当前插件的版本是多少？

现在是2.5.10，但问题还在。这是刚刚截的图，时间依旧是几天前。
![2023-09-03_165715](https://github.com/inu1255/soulsign-chrome/assets/30950457/218681ee-c259-41cb-bf46-3c2ebe82814f)
