### ISSUE TITLE
求大佬写两个地址的签到

### ISSUE THREAD

**Issue by chiyu521** [inu1255/soulsign-chrome#306]
分别是 PT站  https://pthome.net/
阿里云盘 目前的签到脚本也失效了 显示不在线

**Comment by inu1255** [comment]
1. PT没有账号
2. 阿里云盘(作者 @yi-Xu-0100)之前的版本需要定期手动更新 `localStorage` 中的 `refresh_token`。  
魂签2.5.0支持获取 `localStorage` 了，可以试试这个脚本 [aliyundrive.js](https://github.com/inu1255/soulsign-chrome/blob/master/static/demos/aliyundrive.js)
