### ISSUE TITLE
希望能添加通知渠道

### ISSUE THREAD

**Issue by howdareyo** [inu1255/soulsign-chrome#307]
在云服务器上运行时,并不会经常打开查看签到结果,希望增添Webhooks或其他的通知方式以便在签到失败时通知

**Comment by inu1255** [comment]
@howdareyo 2.5.0 支持配置通知渠道
![image](https://github.com/inu1255/soulsign-chrome/assets/5772409/21322f3d-c4c8-499f-a140-d71b5cff9f99)

**Comment by inu1255** [comment]
@howdareyo 已安排
