### ISSUE TITLE
脚本推荐里所列出的脚本不能安装

### ISSUE THREAD

**Issue by zszczh** [inu1255/soulsign-chrome#310]
现象：以“天使动漫_.com”脚本为例，点击”安装“后的新页面会显示以下内容，

找不到文件
Firefox 无法在 moz-extension://2ff56d39-24db-4378-887a-48ff4fb9dc5f/pages/options.html#https://soulsign.inu1255.cn/script/Karanoyo/天使动漫_.com.js 找到该文件。
请检查文件名是否大小写输错，或者有其他输入错误。
请检查文件是否已被移动，重命名或删除。
![image](https://github.com/inu1255/soulsign-chrome/assets/30950457/b5f31527-b126-40a0-8759-f24a1e79e922)

浏览器版本：firefox 116.0.3(64位)

扩展版本：2.5.1

**Comment by inu1255** [comment]
已更新
