### ISSUE TITLE
请问如何解析axios返回的HTML数据

### ISSUE THREAD

**Issue by ACBingo** [inu1255/soulsign-chrome#32]
我自己写了个脚本，但是那个网站是登陆后自动签到，所以我需要直接访问登陆后的网站主页，然后通过判断返回的HTML数据中是否包含某个DOM来判断是否签到成功。

所以通过axios.get()获取这个网站的data数据是html，请问我应该怎么解析呢

我是个java程序员，对js、node了解不多。。

**Comment by inu1255** [comment]
@ACBingo 
1. 简单的可以直接用正则
2. 复杂的可以
var div = document.createElement('div')
div.innerHTML = data;
然后操作div
