### ISSUE TITLE
【建议】希望可以加一个网站快速跳转的按钮

### ISSUE THREAD

**Issue by cooper1x** [inu1255/soulsign-chrome#34]
有的网站不在线，这时候就要快速打开魂签，然后跳转过去。

目前发现京东是不行的，别的好像也不行。

**Comment by huiyadanli** [comment]
建议脚本名的链接修改为网站登录页的链接。。。现在跳转到源码链接有点反直觉

**Comment by cooper1x** [comment]
@huiyadanli 哈哈哈，缘分呐

**Comment by yoyoako** [comment]
这个功能新版已经加上啦
