### ISSUE TITLE
请问如何模拟执行js方法，来签到

### ISSUE THREAD

**Issue by abner0914** [inu1255/soulsign-chrome#40]
首先感谢您开发的插件，非常棒！
1.我尝试学习写了几个脚本，直接访问某个url的，来签到可以实现。
2.请问有的网站，签到是执行js方法的，该如何编写脚本，看了您的那些示例，没找到可以模仿的，能否提供下帮助，写个例子，谢谢。
`<a class="label label-default" href="#" onclick="do_signin(this);"><b>签 到</b></a>`

**Comment by inu1255** [comment]
有两个方法
1. (用魂签实现)所有的签到根本上都是通过调用后端接口实现的，你可能通过这个函数分析它实际调用的哪个接口，参数是怎么生成的，当然如果包含加密参数的话分析起来会比较因难
2. (用其它方案) 比如，写个[油猴](https://greasyfork.org/zh-CN)脚本，或者使用[无头浏览器](https://github.com/GoogleChrome/puppeteer)，但这两种方案都需要打开目标网站的情况下才能签到

**Comment by inu1255** [comment]
已增加模拟点击功能
