### ISSUE TITLE
其他签到

### ISSUE THREAD

**Issue by jarviskao** [inu1255/soulsign-chrome#49]
**悠云矿山论坛**
url: https://www.yymine.com/
[yymine.txt](https://github.com/inu1255/soulsign-chrome/files/3685526/yymine.txt)

**KoolShare**
url: https://koolshare.cn/forum.php
[koolshare.txt](https://github.com/inu1255/soulsign-chrome/files/3685538/koolshare.txt)

**91wii**
url: https://www.91wii.com/
[91wii.txt](https://github.com/inu1255/soulsign-chrome/files/3685543/91wii.txt)

**Comment by bg4vrg** [comment]
多谢，koolshare脚本正需要已取走

**Comment by laincat** [comment]
老大，91wii 改成签到插件了，能更新一下吗？
