### ISSUE TITLE
Notification点击了是不是应该跳转登陆页面

### ISSUE THREAD

**Issue by luanwulin** [inu1255/soulsign-chrome#5]
rt。如果点击了跳转到任务列表没啥必要呢，没登录直接就去登陆呗

**Comment by inu1255** [comment]
为了不打扰用户，不在线提醒有时间间隔；当初是考虑这个间隔时间段可能有多个任务掉线，所以直接跳转到任务列表； 
不过这种情况好像不常见，所以决定在1.0.8中调整
