### ISSUE TITLE
什么值得买签到失败

### ISSUE THREAD

**Issue by YakshaChien** [inu1255/soulsign-chrome#54]
似乎是更改了入口导致的失效。
默认是定位到个人中心，但个人中心已经不能签到了。

**Comment by sununs** [comment]
什么值得买1.01不能签到，测试错误代码9999，好像是referer错误

**Comment by inu1255** [comment]
@sununs Firefox版本有bug导致referer失效，已发布2.02版本修复；
chrome可能会有几次失败，但最后会成功；我没去研究原因

**Comment by sununs** [comment]
> @sununs Firefox版本有bug导致referer失效，已发布2.02版本修复；
> chrome可能会有几次失败，但最后会成功；我没去研究原因
大佬，public下是2.01版本，2.02哪里下载

**Comment by inu1255** [comment]
@sununs 已上架到了[firefox 扩展商店](https://addons.mozilla.org/zh-CN/firefox/addon/%E9%AD%82%E7%AD%BE/versions/)，你也可以自行编译安装
