### ISSUE TITLE
请问能不能自定义签到频率，按小时，按分钟之类的

### ISSUE THREAD

**Issue by ejin** [inu1255/soulsign-chrome#55]
你好，目前翻看了设置和Issues，没有找到控制签到频率的地方，比如设置一天签到几次，或者多少秒，多少分钟签一次（一方面有少数的网站一天可以签多次，有了频率控制后，也可以做很多其他的事情了，不再限于签到），谢谢

**Comment by inu1255** [comment]
一个脚本有两个函数，run是签到函数，目前只允许一天只执行一次；
check是可以指定通过@expire指定执行频率的；

**Comment by ejin** [comment]
> 
> 
> 一个脚本有两个函数，run是签到函数，目前只允许一天只执行一次；
> check是可以指定通过@Expire指定执行频率的；

谢谢，明白了
