### ISSUE TITLE
大神，能否增加一个优酷“零钱+”的签到脚本？

### ISSUE THREAD

**Issue by ugvfpdcuwfnh** [inu1255/soulsign-chrome#57]
优酷APP的“会员免费送”里有个“零钱+”的活动，是优酷和苏州银行联合搞的活动，
分享网址如下：https://ebank.suzhoubank.com/channel/WalletActivity/dist/index.html?Channel=YOUKU&sharekey=d0aee283993dbdb8f423c6e130e09e2e6#/index

我计算了一下，里面1999元的那个套餐性价比挺高，也能随时取出，因为这点钱扔余额宝里一年利息也才70不到，放到这个活动里还能每天领日卡，比买优酷一年VIP划算多了，就是每天领太麻烦 -_-||

求大神做个脚本可好？这个脚本我不会啊   T_T

**Comment by inu1255** [comment]
已经没有了
