### ISSUE TITLE
脚本发布站点注册了也无法查看和安装插件

### ISSUE THREAD

**Issue by sununs** [inu1255/soulsign-chrome#58]
安装提示“{"no":404,"msg":"脚本不存在或无权限"}”

**Comment by sununs** [comment]
是不是什么值得买的1.02智能通过脚本发布站点安装？大佬~

**Comment by inu1255** [comment]
@sununs 站点bug已修复；什么值得买的脚本没有更新1.02，可以直接在源码的public/demo下复制安装

**Comment by sununs** [comment]
发布站点已测试可用
