### ISSUE TITLE
脚本发布平台有bug

### ISSUE THREAD

**Issue by whyjxz14** [inu1255/soulsign-chrome#59]
bug1：
修改的时候切到基础一次下面就会有一个
};
打开的时候会多出两个
};
};
越来越多要手动删除

bug2：
脚本发布平台公开的脚本改成私有以后仍旧会显示。但是报错。

问题1：希望可以删除脚本

**Comment by inu1255** [comment]
bug1: 未复现，是否可以描述详细些
bug2: 已修复
问题1: 已支持

**Comment by whyjxz14** [comment]
> @whyjxz14
> bug1: 未复现，是否可以描述详细些
> bug2: 已修复
> 问题1: 已支持

bug1是域名// @domain那行出了问题。在基础里的域名填了东西以后，切到基础一次再切回源码，下面就会多出一个
};
看他新写的脚本也是这样
https://soulsign.inu1255.cn/script/laincat/%E8%BD%BB%E4%B9%8B%E5%9B%BD%E5%BA%A6.js#soulsign-install
