### ISSUE TITLE
是不是可以把定时器换成chrome.alarms

### ISSUE THREAD

**Issue by luanwulin** [inu1255/soulsign-chrome#6]
rt，如果一直while的话性能不是很高，chrome.alarms直接提供了定时接口

**Comment by inu1255** [comment]
当初图方便，任务数据都存在一个storage里边，多个任务同时读写会出问题；
chrome.alarms和setInterval都可能引起任务并发；
所以采用了while + setTimeout的方式；
由于不影响使用，迫于偷懒这个优化一直没有进行😂

**Comment by luanwulin** [comment]
@inu1255 ( ⊙ o ⊙ )啊！确实可以将就用，不过默认5秒也太快了。还好await会跳出函数，不然一直卡着了😂。我现在改成1小时检查一次了，大佬啥时候优化一把吧~
