### ISSUE TITLE
大佬能否添加几个签到网站，谢谢！

### ISSUE THREAD

**Issue by hrq2797** [inu1255/soulsign-chrome#61]
谢谢大佬
阅次元小说
https://www.abooky.com/plugin.php?id=k_misign:sign

好书友
http://www.93haoshu.com/plugin.php?id=k_misign:sign

gorpg论坛
https://www.gorpg.club/k_misign-sign

**Comment by yi-Xu-0100** [comment]
@hrq2797 阅次元小说签到脚本: https://soulsign.inu1255.cn/scripts/174

**Comment by yi-Xu-0100** [comment]
@hrq2797 好书友签到脚本: https://soulsign.inu1255.cn/scripts/185

**Comment by yi-Xu-0100** [comment]
@hrq2797 gorpg论坛签到脚本：https://soulsign.inu1255.cn/scripts/192

已全部适配。无问题的话，可关闭 issue ~

**Comment by hrq2797** [comment]
> @hrq2797 gorpg论坛签到脚本：https://soulsign.inu1255.cn/scripts/192
> 
> 已全部适配。无问题的话，可关闭 issue ~

谢谢
