### ISSUE TITLE
bilibili直播签到在线状态判断出错

### ISSUE THREAD

**Issue by zhanghua000** [inu1255/soulsign-chrome#64]
如题，每次打开浏览器就会提示bilibili直播在线状态为未登陆，打开登陆网页发现其实已经登陆了，但脚本的登陆状态仍然是未登录。签到功能及签到状态获取正常。因此每次必须在插件里面手动执行一次签到脚本才能签到。

**Comment by sunzehui** [comment]
那个查询在线接口接口换了，替换这个https://api.live.bilibili.com/relation/v1/Feed/heartBeat

**Comment by zhanghua000** [comment]
感谢大佬，已解决
