### ISSUE TITLE
Bug:在编辑脚本界面拖选文本，Chrome会自动关闭编辑窗，Firefox不会

### ISSUE THREAD

**Issue by ejin** [inu1255/soulsign-chrome#69]
由于编辑脚本的窗口较小，拖动文本时，鼠标很容易拖到窗口（文本框）外，松开左键后，Chrome会自动关闭编辑代码的窗口，Firefox不会。
PS：编辑器窗口指的是点击编辑按钮后弹出的这个漂浮小编辑脚本窗口

![微信截图_20200319081212.png](https://i.loli.net/2020/03/19/4Hmnu5a7CZsjAYc.png)

**Comment by inu1255** [comment]
已修改，点击蒙板禁止关闭弹窗
