### ISSUE TITLE
domain 配置失败

### ISSUE THREAD

**Issue by cxfans** [inu1255/soulsign-chrome#71]
按照大佬给的脚本格式 模仿写自用脚本的时候
不知道签到接口后面的一些网址怎么填写
小白一个，希望大佬能指点一下，研究了半天 无论怎么填写都是domain 配置失败

**Comment by cxfans** [comment]
`// ==UserScript==
// @name              爱奇艺签到
// @version           1.0.0
// @author            cxfans
// @loginURL          https://www.iqiyi.com/iframe/loginreg?ver=1
// @expire            900000
// @domain            www.iqiyi.com
// ==/UserScript==

exports.run = async function () {
    var { data } = await axios.get('https://tc.vip.iqiyi.com/taskCenter/task/userSign?P00001=77tShk2SGdg4viP451gTBs0M0r69k09wlEYXm2rxQaWm1CGnYKvCKhm3UTJCPpJCxRM1r5f&platform=b6c13e26323c537d&lang=zh_CN&app_lm=cn&deviceID=&version=');
    var res = JSON.parse(data);
    if (res['code'] == 'A00000') return '签到成功';
    if (res['code'] == 'SIGNED') return '今日已签到';
    return res['msg'];
};
exports.check = async function () {
    var { data } = await axios.get('https://tc.vip.iqiyi.com/taskCenter/task/userSign?P00001=77tShk2SGdg4viP451gTBs0M0r69k09wlEYXm2rxQaWm1CGnYKvCKhm3UTJCPpJCxRM1r5f&platform=b6c13e26323c537d&lang=zh_CN&app_lm=cn&deviceID=&version=');
    var res = JSON.parse(data);
    if (res['ret'] == 'SIGNED') return true;
    return false;
};
`

**Comment by inu1255** [comment]
![image](https://user-images.githubusercontent.com/5772409/78105547-fe755080-7423-11ea-9847-e93299ade65d.png)
你的domain应该配置为 tc.vip.iqiyi.com，注意@domain等应该用小写字母

**Comment by cxfans** [comment]
谢谢大佬，已经成功了！

**Comment by hrq2797** [comment]
大佬是怎么成功的，配置为 tc.vip.iqiyi.com Domain改成小写还是失败了。

**Comment by eno1016** [comment]
请问大佬是怎么成功的。。。一直都失败。。。
能不能跪求个脚本完全体，小白怎么都折腾不明白T^T

**Comment by fujiawei-dev** [comment]
> 请问大佬是怎么成功的。。。一直都失败。。。
> 能不能跪求个脚本完全体，小白怎么都折腾不明白T^T

我这个脚本只能我自己用，别人用不行的，通用的我不会写

**Comment by yi-Xu-0100** [comment]
见 https://github.com/inu1255/soulsign-chrome/issues/90#issuecomment-725951177

**Comment by inu1255** [comment]
项目public/demo目录有脚本示例-------- 原始邮件 --------发件人： Rustle Karl <notifications@github.com>日期： 2020年12月19日周六 下午4:38收件人： inu1255/soulsign-chrome <soulsign-chrome@noreply.github.com>抄送： inu yasha <929909260@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [inu1255/soulsign-chrome] domain 配置失败 (#71)



请问大佬是怎么成功的。。。一直都失败。。。

能不能跪求个脚本完全体，小白怎么都折腾不明白T^T



我这个脚本只能我自己用，别人用不行的，通用的我不会写
