### ISSUE TITLE
脚本安装有问题，安装不上

### ISSUE THREAD

**Issue by XHLYDZ** [inu1255/soulsign-chrome#76]
脚本推荐里的脚本安装失败。

![TIM截图20200507103846](https://user-images.githubusercontent.com/55861090/81248675-7a7c3d00-904f-11ea-9338-13442e6c3c1a.png)
![TIM截图20200507103915](https://user-images.githubusercontent.com/55861090/81248680-7cde9700-904f-11ea-8419-79376395f89c.png)
![TIM截图20200507103925](https://user-images.githubusercontent.com/55861090/81248685-7fd98780-904f-11ea-82af-ca174acd364d.png)

**Comment by inu1255** [comment]
首页直接点安装安装不上是吗，该bug已修复
