### ISSUE TITLE
geekhub签到报错422

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#78]
![image](https://user-images.githubusercontent.com/25523606/83355974-749b2280-a395-11ea-98e8-e5b36e829fd9.png)

![image](https://user-images.githubusercontent.com/25523606/83355978-79f86d00-a395-11ea-81be-cb860299922f.png)

**Comment by yi-Xu-0100** [comment]
https://soulsign.inu1255.cn/scripts/172

我试着写了一个，欢迎验证是否成功，我今天签过了，等明天自己验证……

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/83959895-f965cf00-a8b4-11ea-826b-73103eb08b0b.png)


一直返回422错误

但是我的提交已经和官方的方式一样了，至少我没看出来区别

![image](https://user-images.githubusercontent.com/25523606/83959904-1c907e80-a8b5-11ea-8902-5bf94ba5f447.png)

![image](https://user-images.githubusercontent.com/25523606/83959913-27e3aa00-a8b5-11ea-9bcc-a24e4bacb959.png)

header中部分参数无法修改成和他一样，没办法，我不知道我哪里错了，请求指导，纯新手，摸索求学

**Comment by yi-Xu-0100** [comment]
```
// ==UserScript==
// @name              geekhub
// @namespace         https://soulsign.inu1255.cn?account=yi-Xu-0100
// @version           1.0.3
// @author            yi-Xu-0100
// @loginURL          https://geekhub.com/users/sign_in
// @updateURL         https://soulsign.inu1255.cn/script/yi-Xu-0100/geekhub
// @expire            900000
// @domain            geekhub.com
// ==/UserScript==

exports.run = async function(param) {
let resp = await axios.get("https://geekhub.com/checkins");
    let signhtml = resp.data;
    if (signhtml.includes("今日已签到")){
        return "已经签到过";
    }
    if (signhtml.includes("您需要登录后才能继续")){
        throw "未登录";
    }
    let result = signhtml.match(/<meta name="csrf-token" content="(.*?)"/);
    var { data } = await axios.post('https://geekhub.com/checkins/start', 
{
    "_method": "post",
    "authenticity_token": result[1]
},
{
    transformRequest: [function (data) {
    let ret = ''
    for (let it in data) {
      ret += encodeURIComponent(it) + '=' + encodeURIComponent(data[it]) + '&'
    }
    return ret.substr(0,ret.length-1);
  }],
        headers: {
            "Origin": "https://geekhub.com",
            "Cache-Control": "max-age=0",
            "Upgrade-Insecure-Requests": "1",
            "Referer": "https://geekhub.com/checkins"
        }
});
    if (/今日已签到/.test(data)) return "任务已完成";
    if (/您需要登录后才能继续/.test(data)) throw "未登录";
    
    return "签过了";
};

exports.check = async function(param) {
var {
        status,
        data,
    } = await axios.get(
        "https://geekhub.com/checkins", {
            maxRedirects: 0
        }
    );
    if (/您需要登录后才能继续/.test(data)) return false;
    return true;
};
```

上面是我代码，修改了header，增加了referer，成功，但是origin没有成功修改。

**Comment by inu1255** [comment]
@yi-Xu-0100 这是魂签的bug，origin头修改不会生效；新版本已修复

**Comment by yi-Xu-0100** [comment]
> @yi-Xu-0100 这是魂签的bug，origin头修改不会生效；新版本已修复

新版本只能用压缩包安装吗？谷歌商店的是很久没更新还是？

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/83962862-b9faab00-a8d3-11ea-9b66-e5034c5a2dce.png)

使用build压缩包安装后成功修改origin！

![image](https://user-images.githubusercontent.com/25523606/83962866-c121b900-a8d3-11ea-90a7-17a5b4084bc9.png)

使用测试，应该成功！感谢！

这个测试版的功能和google商店下载的有很多不同，但是google商店的版本号是1.1.2，而这个是1.1.0，是以后只能使用压缩包版更新吗，能提示有新版本吗？

**Comment by yi-Xu-0100** [comment]
> @yi-Xu-0100 这是魂签的bug，origin头修改不会生效；新版本已修复

![image](https://user-images.githubusercontent.com/25523606/83962984-f7ac0380-a8d4-11ea-8bc4-829c0ee1e73c.png)

压缩包的这个**打开扩展网站**是另一个扩展，不知道是不是弄错了:)

![image](https://user-images.githubusercontent.com/25523606/83962996-0b576a00-a8d5-11ea-85fa-fffbb1882d06.png)

**Comment by inu1255** [comment]
@yi-Xu-0100 
1. 功能是对的，打开扩展网站的地址写错了；
2. 这个测试版本是会自动更新的；
4. google商店由于政策调整新版本一直没有通过，我也没什么时间看为啥不通过
