### ISSUE TITLE
SMZDM和京东金融签到失败，B站脚本添加失败

### ISSUE THREAD

**Issue by AlfredQingyao** [inu1255/soulsign-chrome#8]
网页已登录，但是签到不成功，B站脚本添加后会被自动删除

**Comment by inu1255** [comment]
京东金融最近好像改版了，我没找到签到入口，暂时无法修复

**Comment by JackieMium** [comment]
好像不止京东金融，京东的几个这些天都一直提示失败，我无奈只有都关掉了。

**Comment by YakshaChien** [comment]
京东的点一下脚本名进去重新登陆一下，退出来就能签到成功。
但是SMZDM是真的不管用。
虾米签到也不管用，同样，点一下脚本名，跳转个人页面签到+1。
