### ISSUE TITLE
通知怎么关闭?在阻止里阻止 还是出现通知..

### ISSUE THREAD

**Issue by lengshu** [inu1255/soulsign-chrome#91]

**Comment by yi-Xu-0100** [comment]
通知？需要签到的网站不在线的通知吗？

**Comment by lengshu** [comment]
浏览器右下角 弹出的通知..没办法关闭..这里不知道怎么发图..

**Comment by yi-Xu-0100** [comment]
那种不是一段时间不点就会消失？而且一般是提示，某某网站不在线，如果不想对这个网站继续签到了，可以将这个网站的签到脚本关了。

**Comment by inu1255** [comment]
最新版本增加了通知开关，点击插件图标可以设置
