### ISSUE TITLE
求 一个网站签到

### ISSUE THREAD

**Issue by 253253a** [inu1255/soulsign-chrome#96]
https://www.scjuchuang.com/intergralSigin/index 网站是这个 ，这几天过节一直研究，都不会，麻烦老大些支援一下，。
![A9T~(63P`Z `TSZEEZ1Y@WC](https://user-images.githubusercontent.com/67451628/85821649-adb78e80-b7ab-11ea-8f95-8a4836f999ce.png)
![DVI}FITPKP1KM4XFC66848R](https://user-images.githubusercontent.com/67451628/85821712-d0e23e00-b7ab-11ea-804e-cd22780ab94a.png)

**Comment by yi-Xu-0100** [comment]
看了下。个人没法注册……

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/85831930-b0bd7980-b7c1-11ea-836d-3b097b5a8bf3.png)


又看了下，你这个错误，应该是这个网站写错了

**Comment by 253253a** [comment]
老大 我改了网址 还是不行

**Comment by 253253a** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yi_Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月26日(星期五) 下午3:28
收件人:&nbsp;"inu1255/soulsign-chrome"<soulsign-chrome@noreply.github.com&gt;;
抄送:&nbsp;"307292095"<307292095@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [inu1255/soulsign-chrome] 求 一个网站签到 (#96)





 
// ==UserScript==

// @name&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 聚创

// @namespace&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;https://soulsign.inu1255.cn?account=justdo888

// @version&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.0.0

// @author&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 253

// @loginURL&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; https://www.scjuchuang.com/intergralSigin/index

// @updateURL&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;https://soulsign.inu1255.cn/script/justdo888/scjuchuang.com

// @expire&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 900000

// @domain&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; www.scjuchuang.com

// ==/UserScript==




exports.run = async function(param) {

var { data } = await axios.get('https://www.scjuchuang.com/index');

&nbsp; &nbsp; if (/签到成功/.test(data)) return '签到成功';

&nbsp; &nbsp; if (/您今天已经签到过了/.test(data)) return '今日已签';

&nbsp; &nbsp; throw '签到成功';

};




exports.check = async function(param) {

var { data } = await axios.get('https://www.scjuchuang.com/index');

&nbsp; &nbsp; return /欢迎回来/.test(data);

};

**Comment by yi-Xu-0100** [comment]
一般来说，签到的链接，不是进入主页的链接，我没有帐号密码，也没法测试，很难给予相关帮助，现在的报错是什么，你能看到吗？

**Comment by 253253a** [comment]
有QQ吗我加你帮我看看



---原始邮件---
发件人: "yi_Xu"<notifications@github.com&gt;
发送时间: 2020年6月26日(周五) 下午4:13
收件人: "inu1255/soulsign-chrome"<soulsign-chrome@noreply.github.com&gt;;
抄送: "253253a"<307292095@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [inu1255/soulsign-chrome] 求 一个网站签到 (#96)




 
一般来说，签到的链接，不是进入主页的链接，我没有帐号密码，也没法测试，很难给予相关帮助，现在的报错是什么，你能看到吗？

**Comment by yi-Xu-0100** [comment]
yi_Xu@yixuju.cn 发我邮箱 @253253a
