### ISSUE TITLE
模拟登陆无效，疑似需要修改 cookie

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/soulsign-chrome#97]
今天使用 axios 去模拟登陆了某网站，返回的数据中有回执显示是登陆成功。但是我重新获取主页的信息的时候，发现没有登陆的效果。

不知道这个怎么解决？或者应该以什么方式去模拟登陆？

我看了下，回执中还给了一个 data, 应该是需要修改的 cookie 中的 user_info，但是我没有权限修改下一条获取主页的请求的 cookie ，这个应该怎么传递 cookie，以让这个登陆效果被保存下来？

**Comment by inu1255** [comment]
@yi-Xu-0100  已提交更新，增加setCookie(url, name, value)函数来修改cookie，需要@grant cookie 申请cookie权限
